import { jsPDF } from "jspdf";

const INK = "#0a0b0d";
const PAPER = "#fcfbf7";
const LIME = "#d4f570";
const MUTED = "#6b7280";
const LINE = "#e5e7eb";
const EMERALD = "#0f5f3f";

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;

const fmtMoney = (n, ccy = "USD") =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: ccy, minimumFractionDigits: 2 }).format(n || 0);

const fmtNgn = (n) =>
  "NGN " + new Intl.NumberFormat("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n || 0);

const fmtDate = (iso) => {
  if (!iso) return "—";
  const d = new Date(iso);
  return d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
};

const fmtDateTime = (iso) => {
  if (!iso) return "—";
  const d = new Date(iso);
  return d.toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
};

const ref = (id) => "QU-" + String(id || "").slice(0, 4).toUpperCase();

function drawHeader(doc, title) {
  doc.setFillColor(INK);
  doc.rect(0, 0, PAGE_W, 24, "F");

  doc.setFillColor(LIME);
  doc.roundedRect(MARGIN, 8, 8, 8, 1.5, 1.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text("X", MARGIN + 4, 13.8, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(PAPER);
  doc.text("XaePay", MARGIN + 12, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(LIME);
  doc.text(title.toUpperCase(), PAGE_W - MARGIN, 14, { align: "right" });
}

function drawFooter(doc, page, total) {
  const y = PAGE_H - 12;
  doc.setDrawColor(LINE);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, y - 4, PAGE_W - MARGIN, y - 4);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(MUTED);
  doc.text("Generated by XaePay  |  Funds custody by licensed payment partner.  |  XaePay is a software/compliance layer that does not custody funds.", MARGIN, y);
  doc.text(`Page ${page} of ${total}`, PAGE_W - MARGIN, y, { align: "right" });
}

function drawLabelValue(doc, label, value, x, y, valueOpts = {}) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(MUTED);
  doc.text(label.toUpperCase(), x, y);

  doc.setFont(valueOpts.mono ? "courier" : "helvetica", valueOpts.bold ? "bold" : "normal");
  doc.setFontSize(valueOpts.size || 10);
  doc.setTextColor(valueOpts.color || INK);
  const v = String(value ?? "—");
  doc.text(v, x, y + 5);
  return y + (valueOpts.lineHeight || 11);
}

function buildPaymentInstructionsPage(doc, q) {
  drawHeader(doc, "Payment Instructions");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Deposit instructions", MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(`To complete your trade payment to ${q.beneficiary || "your supplier"}, deposit the amount below using the bank details on this page.`, MARGIN, y, { maxWidth: CONTENT_W });
  y += 12;

  doc.setFillColor(INK);
  doc.roundedRect(MARGIN, y, CONTENT_W, 40, 3, 3, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(LIME);
  doc.text("AMOUNT TO DEPOSIT", MARGIN + 8, y + 9);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(PAPER);
  const ngnTotal = q.ngn_total || (q.amount && q.rate ? q.amount * q.rate : 0);
  doc.text(fmtNgn(ngnTotal), MARGIN + 8, y + 24);

  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor(LIME);
  doc.text(`Reference  ${ref(q.id)}`, MARGIN + 8, y + 34);
  y += 50;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Bank details", MARGIN, y);
  y += 7;

  const bank = q.cedar_bank_details || {};
  const rows = [
    ["Bank name", bank.bank_name || bank.bankName || "—"],
    ["Account name", bank.account_name || bank.accountName || "—"],
    ["Account number", bank.account_number || bank.accountNumber || "—"],
    ["Sort / routing code", bank.sort_code || bank.sortCode || bank.routing_number || "—"],
    ["Reference (use exactly this)", ref(q.id)],
  ];

  doc.setDrawColor(LINE);
  doc.setLineWidth(0.2);
  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(label.toUpperCase(), MARGIN, y);

    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });

    doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
    y += 9;
  });
  y += 6;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("What happens next", MARGIN, y);
  y += 7;

  const steps = [
    "Use the exact reference above when making the deposit. Without it your payment may not be matched.",
    `Deposit must be made before ${fmtDateTime(q.expires_at)} for the locked rate to apply.`,
    `Once received, your operator (${q.bdc_name || "—"}) will release ${fmtMoney(q.amount, q.currency)} to ${q.beneficiary || "your supplier"} the same business day.`,
    "You will receive a WhatsApp + email notification at every step until funds are confirmed delivered.",
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(INK);
  steps.forEach((step, i) => {
    doc.text(`${i + 1}.`, MARGIN, y);
    const lines = doc.splitTextToSize(step, CONTENT_W - 6);
    doc.text(lines, MARGIN + 5, y);
    y += lines.length * 4.5 + 2;
  });

  y += 4;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`ISSUED BY  ${(q.bdc_name || "your operator").toUpperCase()}`, MARGIN, y);
  doc.text(`ISSUED  ${fmtDate(q.created_at)}`, PAGE_W - MARGIN, y, { align: "right" });
}

function buildInvoicePage(doc, q) {
  drawHeader(doc, "Invoice");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Invoice", MARGIN, y);

  doc.setFont("courier", "normal");
  doc.setFontSize(11);
  doc.setTextColor(MUTED);
  doc.text(ref(q.id), PAGE_W - MARGIN, y, { align: "right" });
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(`Issued ${fmtDate(q.created_at)}`, MARGIN, y);
  y += 14;

  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Issued by", q.bdc_name || "Your operator", MARGIN, y);
  drawLabelValue(doc, "Bill to", q.customer_name || "Customer", MARGIN + colW + 8, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(q.bdc_phone || "Operator contact", MARGIN, y + 11);
  doc.text([q.customer_phone, q.customer_email].filter(Boolean).join("  ·  ") || "—", MARGIN + colW + 8, y + 11);
  y += 22;

  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("DESCRIPTION", MARGIN, y);
  doc.text("AMOUNT", PAGE_W - MARGIN, y, { align: "right" });
  y += 5;
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  const desc = `Cross-border trade payment to ${q.beneficiary || "supplier"}${q.destination ? ` (${q.destination})` : ""}`;
  doc.text(desc, MARGIN, y, { maxWidth: CONTENT_W - 50 });
  doc.setFont("courier", "normal");
  doc.text(fmtMoney(q.amount, q.currency || "USD"), PAGE_W - MARGIN, y, { align: "right" });
  y += 12;

  if (q.invoice_payment_label) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(q.invoice_payment_label, MARGIN, y);
    y += 6;
  }

  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  const sumX = PAGE_W - MARGIN - 60;
  const drawSummaryRow = (label, value, opts = {}) => {
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(opts.size || 9);
    doc.setTextColor(opts.color || INK);
    doc.text(label, sumX, y);
    doc.setFont("courier", opts.bold ? "bold" : "normal");
    doc.text(value, PAGE_W - MARGIN, y, { align: "right" });
    y += opts.lineHeight || 6;
  };

  drawSummaryRow("Subtotal", fmtMoney(q.amount, q.currency || "USD"));
  drawSummaryRow("Exchange rate", `${(q.rate || 0).toFixed(2)} NGN / ${q.currency || "USD"}`);
  y += 2;
  doc.setDrawColor(INK);
  doc.line(sumX, y, PAGE_W - MARGIN, y);
  y += 6;
  const ngnTotal = q.ngn_total || (q.amount && q.rate ? q.amount * q.rate : 0);
  drawSummaryRow("Total", fmtNgn(ngnTotal), { bold: true, size: 12, lineHeight: 8 });

  y += 10;

  if (q.invoice_total_amount) {
    doc.setFillColor(255, 247, 213);
    doc.setDrawColor(252, 211, 77);
    doc.roundedRect(MARGIN, y, CONTENT_W, 14, 2, 2, "FD");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(INK);
    const note = `This payment is part of a larger invoice (full value ${fmtMoney(q.invoice_total_amount, q.invoice_total_currency || "USD")}). Track the full invoice with your operator.`;
    doc.text(note, MARGIN + 4, y + 9, { maxWidth: CONTENT_W - 8 });
    y += 18;
  }

  const noteY = PAGE_H - 35;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("This invoice records a cross-border trade payment facilitated by XaePay. Funds custody is provided by a licensed payment partner.", MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Questions? Reply to your operator on WhatsApp using the number you were quoted from.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateQuotePdf(quote) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildPaymentInstructionsPage(doc, quote);
  drawFooter(doc, 1, 2);
  doc.addPage();
  buildInvoicePage(doc, quote);
  drawFooter(doc, 2, 2);
  return doc;
}

export function downloadQuotePdf(doc, quoteId) {
  doc.save(`${ref(quoteId)}-XaePay.pdf`);
}

// === Compliance pack PDF =====================================================
// Per-customer compliance pack — issued by the operator to honor the
// Compliance Pro tier "quarterly compliance pack" deliverable. Lists all
// uploaded compliance documents, their status against tier requirements,
// and an audit summary.

function buildCompliancePackPage(doc, customer, docsByType, requirements, tier, operatorName) {
  drawHeader(doc, "Compliance Pack");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Compliance pack", MARGIN, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  const periodLabel = new Date().toLocaleDateString("en-GB", { month: "long", year: "numeric" });
  doc.text(`${customer.name || "Customer"} · ${periodLabel}`, MARGIN, y);
  y += 12;

  // Two-column header summary: customer | operator
  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Customer", customer.name || "—", MARGIN, y);
  drawLabelValue(doc, "Issued by", operatorName || "Operator", MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text([customer.phone, customer.email].filter(Boolean).join("  ·  ") || "—", MARGIN, y + 11);
  doc.text(`Tier: ${tier.toUpperCase()}`, MARGIN + colW + 8, y + 11);
  y += 22;

  // KYC + Cedar status pills
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Identity & licensing", MARGIN, y);
  y += 7;

  const idRows = [
    ["KYC status", (customer.cedar_kyc_status || customer.kyc_status || "Pending").toString().toUpperCase()],
    ["KYC tier", String(customer.kyc_tier ?? "0")],
    ["Cedar business ID", customer.cedar_business_id ? String(customer.cedar_business_id) : "—"],
    ["Customer type", customer.type || "—"],
  ];
  idRows.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(label.toUpperCase(), MARGIN, y);
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });
    doc.setDrawColor(LINE);
    doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
    y += 9;
  });
  y += 4;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Compliance documents", MARGIN, y);
  y += 6;

  if (!requirements || requirements.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("No documents required by this tier.", MARGIN, y);
    return;
  }

  // Table header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("DOCUMENT", MARGIN, y + 5);
  doc.text("ISSUED", MARGIN + 70, y + 5);
  doc.text("EXPIRES", MARGIN + 105, y + 5);
  doc.text("STATUS", PAGE_W - MARGIN, y + 5, { align: "right" });
  y += 8;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  requirements.forEach((r) => {
    const d = docsByType[r.docType];
    const expiresAt = d?.expires_at ? new Date(d.expires_at) : (d?.issued_at && r.refreshDays ? new Date(new Date(d.issued_at).getTime() + r.refreshDays * 86400000) : null);
    let status = "Missing";
    let statusColor = "#6b7280";
    if (d) {
      if (!r.refreshDays) { status = "Valid"; statusColor = EMERALD; }
      else if (expiresAt) {
        const days = Math.floor((expiresAt.getTime() - Date.now()) / 86400000);
        if (days < 0) { status = "Expired"; statusColor = "#991b1b"; }
        else if (days <= 14) { status = "Expiring"; statusColor = "#92400e"; }
        else { status = "Valid"; statusColor = EMERALD; }
      }
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(INK);
    doc.text(r.label, MARGIN, y, { maxWidth: 65 });

    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(d?.issued_at ? fmtDate(d.issued_at) : "—", MARGIN + 70, y);
    doc.text(expiresAt ? fmtDate(expiresAt.toISOString()) : (r.refreshDays ? "—" : "no expiry"), MARGIN + 105, y);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(statusColor);
    doc.text(status, PAGE_W - MARGIN, y, { align: "right" });

    doc.setDrawColor(LINE);
    doc.line(MARGIN, y + 3, PAGE_W - MARGIN, y + 3);
    y += 8;
  });

  // Footer note
  const noteY = PAGE_H - 35;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`This compliance pack reflects ${customer.name || "the customer"}'s document status at ${new Date().toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" })}.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Generated by XaePay's compliance agent. For Cedar Money's compliance team, verify each document against Cedar's records via the customer's onboarded business ID.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateCompliancePackPdf({ customer, docs, requirements, tier, operatorName }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  // Group docs by doc_type, keeping the latest per type
  const docsByType = {};
  for (const d of docs || []) {
    const existing = docsByType[d.doc_type];
    if (!existing) docsByType[d.doc_type] = d;
    else {
      const exp1 = existing.expires_at || existing.issued_at || existing.created_at || "";
      const exp2 = d.expires_at || d.issued_at || d.created_at || "";
      if (exp2 > exp1) docsByType[d.doc_type] = d;
    }
  }
  buildCompliancePackPage(doc, customer, docsByType, requirements, tier || "pro", operatorName);
  drawFooter(doc, 1, 1);
  return doc;
}

// === Transaction confirmation PDF ============================================
// Auto-generated receipt for a completed transaction. Available to both
// operator and customer the moment the transaction's status flips to filled
// (or Cedar reports COMPLETED / payout ARRIVED). Independent of Cedar's MT103 —
// the MT103 is a separate bank-confirmation doc that gets uploaded into the
// transaction's supporting documents once the operator has it.

function buildTransactionConfirmationPage(doc, q, operatorName) {
  drawHeader(doc, "Transaction Confirmation");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Confirmation", MARGIN, y);

  doc.setFont("courier", "normal");
  doc.setFontSize(11);
  doc.setTextColor(MUTED);
  doc.text(ref(q.id), PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(`Status: COMPLETED · Issued ${fmtDateTime(q.filled_at || q.cedar_request_status_updated_at || q.created_at)}`, MARGIN, y);
  y += 12;

  // Big amount card
  doc.setFillColor(INK);
  doc.roundedRect(MARGIN, y, CONTENT_W, 38, 3, 3, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(LIME);
  doc.text("AMOUNT PROCESSED", MARGIN + 8, y + 9);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(PAPER);
  doc.text(fmtMoney(q.amount, q.currency || "USD"), MARGIN + 8, y + 24);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor(LIME);
  doc.text(`Customer paid  ${fmtNgn(q.ngn_total)}  @  ₦${parseFloat(q.rate || 0).toFixed(2)}/$`, MARGIN + 8, y + 33);
  y += 48;

  // Parties
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Parties", MARGIN, y);
  y += 6;

  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Customer", q.customer_name || "—", MARGIN, y);
  drawLabelValue(doc, "Recipient / supplier", q.beneficiary || "—", MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text([q.customer_phone, q.customer?.email].filter(Boolean).join("  ·  ") || "—", MARGIN, y + 11);
  doc.text(q.destination || "—", MARGIN + colW + 8, y + 11);
  y += 20;

  drawLabelValue(doc, "Issued by", operatorName || q.bdc_name || "Operator", MARGIN, y);
  drawLabelValue(doc, "Settled via", "Licensed payment partner", MARGIN + colW + 8, y);
  y += 16;

  // Transaction details table
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Transaction details", MARGIN, y);
  y += 7;

  const rows = [
    ["Reference", ref(q.id)],
    ["Amount", `${fmtMoney(q.amount, q.currency || "USD")}`],
    ["Customer rate", `₦${parseFloat(q.rate || 0).toFixed(2)} / $`],
    ["Customer paid (NGN)", fmtNgn(q.ngn_total)],
    ["Purpose", q.cedar_purpose || "GOODS_PURCHASED"],
    ["Status", "COMPLETED"],
    ["Completed at", fmtDateTime(q.filled_at || q.cedar_request_status_updated_at)],
  ];
  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(label.toUpperCase(), MARGIN, y);
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });
    doc.setDrawColor(LINE);
    doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
    y += 9;
  });

  // Bank details (if present from Cedar response)
  const bank = q.cedar_bank_details || {};
  const bankName = bank.bank_name || bank.bankName;
  if (bankName) {
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(INK);
    doc.text("Settlement route", MARGIN, y);
    y += 7;
    const bankRows = [
      ["Bank", bankName],
      ["Account name", bank.account_name || bank.accountName || "—"],
      ["Account number", bank.account_number || bank.accountNumber || "—"],
      ["Reference", ref(q.id)],
    ];
    bankRows.forEach(([label, value]) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text(label.toUpperCase(), MARGIN, y);
      doc.setFont("courier", "normal");
      doc.setFontSize(10);
      doc.setTextColor(INK);
      doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });
      doc.setDrawColor(LINE);
      doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
      y += 9;
    });
  }

  // Footer note
  const noteY = PAGE_H - 35;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("This confirmation is generated automatically by XaePay when a cross-border trade payment completes. The MT103 / SWIFT wire confirmation is a separate document issued by the licensed payment partner; once available it will be attached to this transaction.", MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Powered by XaePay · Software/compliance layer · Funds custody by licensed payment partner.", MARGIN, noteY + 17, { maxWidth: CONTENT_W });
}

export function generateTransactionConfirmationPdf({ quote, operatorName }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildTransactionConfirmationPage(doc, quote, operatorName);
  drawFooter(doc, 1, 1);
  return doc;
}

export function downloadTransactionConfirmationPdf(doc, quote) {
  doc.save(`${ref(quote.id)}-confirmation-XaePay.pdf`);
}

export function downloadCompliancePackPdf(doc, customer) {
  const safeName = (customer?.name || "Customer").replace(/[^\w]+/g, "_");
  const period = new Date().toLocaleDateString("en-GB", { month: "short", year: "numeric" }).replace(/\s+/g, "_");
  doc.save(`${safeName}_compliance_pack_${period}.pdf`);
}

export const _refForFilename = ref;
