import { jsPDF } from "jspdf";

const INK = "#0a0b0d";
const PAPER = "#fcfbf7";
const LIME = "#d4f570";
const MUTED = "#6b7280";
const LINE = "#e5e7eb";
const EMERALD = "#0f5f3f";

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;

const fmtMoney = (n, ccy = "USD") =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: ccy, minimumFractionDigits: 2 }).format(n || 0);

const fmtNgn = (n) =>
  "NGN " + new Intl.NumberFormat("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n || 0);

const fmtDate = (iso) => {
  if (!iso) return "—";
  const d = new Date(iso);
  return d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
};

const fmtDateTime = (iso) => {
  if (!iso) return "—";
  const d = new Date(iso);
  return d.toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
};

const ref = (id) => "QU-" + String(id || "").slice(0, 4).toUpperCase();

function drawHeader(doc, title, accentColor) {
  // Branded business invoices tint the header with the operator's accent color
  // (or fall back to the default INK). The XaePay X-block stays as a small
  // platform attribution mark — required for the compliance disclosure even
  // when the operator has their own brand.
  const headerFill = accentColor && accentColor !== INK ? accentColor : INK;
  doc.setFillColor(headerFill);
  doc.rect(0, 0, PAGE_W, 24, "F");

  doc.setFillColor(LIME);
  doc.roundedRect(MARGIN, 8, 8, 8, 1.5, 1.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text("X", MARGIN + 4, 13.8, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(PAPER);
  doc.text("XaePay", MARGIN + 12, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(LIME);
  doc.text(title.toUpperCase(), PAGE_W - MARGIN, 14, { align: "right" });
}

function drawFooter(doc, page, total) {
  const y = PAGE_H - 12;
  doc.setDrawColor(LINE);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, y - 4, PAGE_W - MARGIN, y - 4);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(MUTED);
  doc.text("Generated by XaePay  |  Funds custody by licensed payment partner.  |  XaePay is a software/compliance layer that does not custody funds.", MARGIN, y);
  doc.text(`Page ${page} of ${total}`, PAGE_W - MARGIN, y, { align: "right" });
}

function drawLabelValue(doc, label, value, x, y, valueOpts = {}) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(MUTED);
  doc.text(label.toUpperCase(), x, y);

  doc.setFont(valueOpts.mono ? "courier" : "helvetica", valueOpts.bold ? "bold" : "normal");
  doc.setFontSize(valueOpts.size || 10);
  doc.setTextColor(valueOpts.color || INK);
  const v = String(value ?? "—");
  doc.text(v, x, y + 5);
  return y + (valueOpts.lineHeight || 11);
}

function buildPaymentInstructionsPage(doc, q) {
  drawHeader(doc, "Payment Instructions");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Deposit instructions", MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(`To complete your trade payment to ${q.beneficiary || "your supplier"}, deposit the amount below using the bank details on this page.`, MARGIN, y, { maxWidth: CONTENT_W });
  y += 12;

  doc.setFillColor(INK);
  doc.roundedRect(MARGIN, y, CONTENT_W, 40, 3, 3, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(LIME);
  doc.text("AMOUNT TO DEPOSIT", MARGIN + 8, y + 9);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(PAPER);
  const ngnTotal = q.ngn_total || (q.amount && q.rate ? q.amount * q.rate : 0);
  doc.text(fmtNgn(ngnTotal), MARGIN + 8, y + 24);

  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor(LIME);
  doc.text(`Reference  ${ref(q.id)}`, MARGIN + 8, y + 34);
  y += 50;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Bank details", MARGIN, y);
  y += 7;

  const bank = q.cedar_bank_details || {};
  const rows = [
    ["Bank name", bank.bank_name || bank.bankName || "—"],
    ["Account name", bank.account_name || bank.accountName || "—"],
    ["Account number", bank.account_number || bank.accountNumber || "—"],
    ["Sort / routing code", bank.sort_code || bank.sortCode || bank.routing_number || "—"],
    ["Reference (use exactly this)", ref(q.id)],
  ];

  doc.setDrawColor(LINE);
  doc.setLineWidth(0.2);
  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(label.toUpperCase(), MARGIN, y);

    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });

    doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
    y += 9;
  });
  y += 6;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("What happens next", MARGIN, y);
  y += 7;

  const steps = [
    "Use the exact reference above when making the deposit. Without it your payment may not be matched.",
    `Deposit must be made before ${fmtDateTime(q.expires_at)} for the locked rate to apply.`,
    `Once received, your operator (${q.bdc_name || "—"}) will release ${fmtMoney(q.amount, q.currency)} to ${q.beneficiary || "your supplier"} the same business day.`,
    "You will receive a WhatsApp + email notification at every step until funds are confirmed delivered.",
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(INK);
  steps.forEach((step, i) => {
    doc.text(`${i + 1}.`, MARGIN, y);
    const lines = doc.splitTextToSize(step, CONTENT_W - 6);
    doc.text(lines, MARGIN + 5, y);
    y += lines.length * 4.5 + 2;
  });

  y += 4;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`ISSUED BY  ${(q.bdc_name || "your operator").toUpperCase()}`, MARGIN, y);
  doc.text(`ISSUED  ${fmtDate(q.created_at)}`, PAGE_W - MARGIN, y, { align: "right" });
}

function buildInvoicePage(doc, q) {
  drawHeader(doc, "Invoice");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Invoice", MARGIN, y);

  doc.setFont("courier", "normal");
  doc.setFontSize(11);
  doc.setTextColor(MUTED);
  doc.text(ref(q.id), PAGE_W - MARGIN, y, { align: "right" });
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(`Issued ${fmtDate(q.created_at)}`, MARGIN, y);
  y += 14;

  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Issued by", q.bdc_name || "Your operator", MARGIN, y);
  drawLabelValue(doc, "Bill to", q.customer_name || "Customer", MARGIN + colW + 8, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(q.bdc_phone || "Operator contact", MARGIN, y + 11);
  doc.text([q.customer_phone, q.customer_email].filter(Boolean).join("  ·  ") || "—", MARGIN + colW + 8, y + 11);
  y += 22;

  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("DESCRIPTION", MARGIN, y);
  doc.text("AMOUNT", PAGE_W - MARGIN, y, { align: "right" });
  y += 5;
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  const desc = `Cross-border trade payment to ${q.beneficiary || "supplier"}${q.destination ? ` (${q.destination})` : ""}`;
  doc.text(desc, MARGIN, y, { maxWidth: CONTENT_W - 50 });
  doc.setFont("courier", "normal");
  doc.text(fmtMoney(q.amount, q.currency || "USD"), PAGE_W - MARGIN, y, { align: "right" });
  y += 12;

  if (q.invoice_payment_label) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(q.invoice_payment_label, MARGIN, y);
    y += 6;
  }

  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  const sumX = PAGE_W - MARGIN - 60;
  const drawSummaryRow = (label, value, opts = {}) => {
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(opts.size || 9);
    doc.setTextColor(opts.color || INK);
    doc.text(label, sumX, y);
    doc.setFont("courier", opts.bold ? "bold" : "normal");
    doc.text(value, PAGE_W - MARGIN, y, { align: "right" });
    y += opts.lineHeight || 6;
  };

  drawSummaryRow("Subtotal", fmtMoney(q.amount, q.currency || "USD"));
  drawSummaryRow("Exchange rate", `${(q.rate || 0).toFixed(2)} NGN / ${q.currency || "USD"}`);
  y += 2;
  doc.setDrawColor(INK);
  doc.line(sumX, y, PAGE_W - MARGIN, y);
  y += 6;
  const ngnTotal = q.ngn_total || (q.amount && q.rate ? q.amount * q.rate : 0);
  drawSummaryRow("Total", fmtNgn(ngnTotal), { bold: true, size: 12, lineHeight: 8 });

  y += 10;

  if (q.invoice_total_amount) {
    doc.setFillColor(255, 247, 213);
    doc.setDrawColor(252, 211, 77);
    doc.roundedRect(MARGIN, y, CONTENT_W, 14, 2, 2, "FD");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(INK);
    const note = `This payment is part of a larger invoice (full value ${fmtMoney(q.invoice_total_amount, q.invoice_total_currency || "USD")}). Track the full invoice with your operator.`;
    doc.text(note, MARGIN + 4, y + 9, { maxWidth: CONTENT_W - 8 });
    y += 18;
  }

  const noteY = PAGE_H - 35;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("This invoice records a cross-border trade payment facilitated by XaePay. Funds custody is provided by a licensed payment partner.", MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Questions? Reply to your operator on WhatsApp using the number you were quoted from.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateQuotePdf(quote) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildPaymentInstructionsPage(doc, quote);
  drawFooter(doc, 1, 2);
  doc.addPage();
  buildInvoicePage(doc, quote);
  drawFooter(doc, 2, 2);
  return doc;
}

export function downloadQuotePdf(doc, quoteId) {
  doc.save(`${ref(quoteId)}-XaePay.pdf`);
}

// === Compliance pack PDF =====================================================
// Per-customer compliance pack — issued by the operator to honor the
// Compliance Pro tier "quarterly compliance pack" deliverable. Lists all
// uploaded compliance documents, their status against tier requirements,
// and an audit summary.

function buildCompliancePackPage(doc, customer, docsByType, requirements, tier, operatorName) {
  drawHeader(doc, "Compliance Pack");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Compliance pack", MARGIN, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  const periodLabel = new Date().toLocaleDateString("en-GB", { month: "long", year: "numeric" });
  doc.text(`${customer.name || "Customer"} · ${periodLabel}`, MARGIN, y);
  y += 12;

  // Two-column header summary: customer | operator
  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Customer", customer.name || "—", MARGIN, y);
  drawLabelValue(doc, "Issued by", operatorName || "Operator", MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text([customer.phone, customer.email].filter(Boolean).join("  ·  ") || "—", MARGIN, y + 11);
  doc.text(`Tier: ${tier.toUpperCase()}`, MARGIN + colW + 8, y + 11);
  y += 22;

  // KYC + Cedar status pills
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Identity & licensing", MARGIN, y);
  y += 7;

  const idRows = [
    ["KYC status", (customer.cedar_kyc_status || customer.kyc_status || "Pending").toString().toUpperCase()],
    ["KYC tier", String(customer.kyc_tier ?? "0")],
    ["Cedar business ID", customer.cedar_business_id ? String(customer.cedar_business_id) : "—"],
    ["Customer type", customer.type || "—"],
  ];
  idRows.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(label.toUpperCase(), MARGIN, y);
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });
    doc.setDrawColor(LINE);
    doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
    y += 9;
  });
  y += 4;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Compliance documents", MARGIN, y);
  y += 6;

  if (!requirements || requirements.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("No documents required by this tier.", MARGIN, y);
    return;
  }

  // Table header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("DOCUMENT", MARGIN, y + 5);
  doc.text("ISSUED", MARGIN + 70, y + 5);
  doc.text("EXPIRES", MARGIN + 105, y + 5);
  doc.text("STATUS", PAGE_W - MARGIN, y + 5, { align: "right" });
  y += 8;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  requirements.forEach((r) => {
    const d = docsByType[r.docType];
    const expiresAt = d?.expires_at ? new Date(d.expires_at) : (d?.issued_at && r.refreshDays ? new Date(new Date(d.issued_at).getTime() + r.refreshDays * 86400000) : null);
    let status = "Missing";
    let statusColor = "#6b7280";
    if (d) {
      if (!r.refreshDays) { status = "Valid"; statusColor = EMERALD; }
      else if (expiresAt) {
        const days = Math.floor((expiresAt.getTime() - Date.now()) / 86400000);
        if (days < 0) { status = "Expired"; statusColor = "#991b1b"; }
        else if (days <= 14) { status = "Expiring"; statusColor = "#92400e"; }
        else { status = "Valid"; statusColor = EMERALD; }
      }
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(INK);
    doc.text(r.label, MARGIN, y, { maxWidth: 65 });

    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(d?.issued_at ? fmtDate(d.issued_at) : "—", MARGIN + 70, y);
    doc.text(expiresAt ? fmtDate(expiresAt.toISOString()) : (r.refreshDays ? "—" : "no expiry"), MARGIN + 105, y);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(statusColor);
    doc.text(status, PAGE_W - MARGIN, y, { align: "right" });

    doc.setDrawColor(LINE);
    doc.line(MARGIN, y + 3, PAGE_W - MARGIN, y + 3);
    y += 8;
  });

  // Footer note
  const noteY = PAGE_H - 35;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`This compliance pack reflects ${customer.name || "the customer"}'s document status at ${new Date().toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" })}.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Generated by XaePay's compliance agent. For Cedar Money's compliance team, verify each document against Cedar's records via the customer's onboarded business ID.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

// Per-transaction audit page — lists each completed transaction in the period
// with its trade-doc supporting docs status. Bank partners review this in the
// quarterly compliance check.
function buildTransactionsAuditPage(doc, customer, completedTransactions, transactionRequirements) {
  drawHeader(doc, "Transactions Audit");

  let y = 38;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Transactions audit", MARGIN, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(`${customer.name || "Customer"} · ${completedTransactions.length} completed transaction${completedTransactions.length === 1 ? "" : "s"} in this period`, MARGIN, y);
  y += 12;

  if (completedTransactions.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(MUTED);
    doc.text("No completed transactions in this audit period.", MARGIN, y);
    return;
  }

  completedTransactions.forEach((t, i) => {
    // Page-break if running low on space
    if (y > PAGE_H - 70) {
      drawFooter(doc, doc.internal.getNumberOfPages(), 0);
      doc.addPage();
      drawHeader(doc, "Transactions Audit (cont.)");
      y = 38;
    }

    const txRef = "QU-" + String(t.id || "").slice(0, 4).toUpperCase();
    const txTier = (t.review_tier || "verified").toLowerCase();
    const txReqs = transactionRequirements[txTier] || [];

    // Block header
    doc.setFillColor(247, 245, 240); // bone
    doc.roundedRect(MARGIN, y, CONTENT_W, 11, 1.5, 1.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(INK);
    doc.text(txRef, MARGIN + 3, y + 7);
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.text(`${fmtMoney(t.amount, t.currency || "USD")}  →  ${t.beneficiary || t.destination || "—"}`, MARGIN + 22, y + 7);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(`${txTier.toUpperCase()} · ${fmtDate(t.filled_at || t.created_at)}`, PAGE_W - MARGIN, y + 7, { align: "right" });
    y += 13;

    // Trade docs status
    if (txReqs.length === 0) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(MUTED);
      doc.text("No trade docs required at this tier.", MARGIN + 3, y);
      y += 7;
    } else {
      const txDocsByType = {};
      for (const d of t.docs || []) {
        if (!txDocsByType[d.doc_type]) txDocsByType[d.doc_type] = d;
      }
      txReqs.forEach((r) => {
        const present = !!txDocsByType[r.docType];
        const statusColor = present ? EMERALD : (r.severity === "hard" ? "#991b1b" : "#92400e");
        const statusLabel = present ? "Uploaded" : (r.severity === "hard" ? "MISSING" : "Recommended");
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(INK);
        doc.text(`  •  ${r.label}`, MARGIN + 3, y);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        doc.setTextColor(statusColor);
        doc.text(statusLabel, PAGE_W - MARGIN, y, { align: "right" });
        y += 6;
      });
    }
    y += 4;
  });

  // Audit footer
  if (y < PAGE_H - 30) {
    const noteY = PAGE_H - 30;
    doc.setDrawColor(LINE);
    doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text("Each transaction's trade documents back up the original invoice. Documents marked MISSING for hard-required types should be remediated before the next quarterly review window closes.", MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  }
}

export function generateCompliancePackPdf({ customer, docs, requirements, tier, operatorName, completedTransactions, transactionRequirements }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  // Group customer-level docs by doc_type, keeping the latest per type
  const docsByType = {};
  for (const d of docs || []) {
    const existing = docsByType[d.doc_type];
    if (!existing) docsByType[d.doc_type] = d;
    else {
      const exp1 = existing.expires_at || existing.issued_at || existing.created_at || "";
      const exp2 = d.expires_at || d.issued_at || d.created_at || "";
      if (exp2 > exp1) docsByType[d.doc_type] = d;
    }
  }
  buildCompliancePackPage(doc, customer, docsByType, requirements, tier || "pro", operatorName);
  drawFooter(doc, 1, 0); // pageCount filled in at save time

  // Add transactions audit page if we have completed transactions to report on
  if (completedTransactions && completedTransactions.length > 0 && transactionRequirements) {
    doc.addPage();
    buildTransactionsAuditPage(doc, customer, completedTransactions, transactionRequirements);
    drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  }
  return doc;
}

// === Transaction confirmation PDF ============================================
// Auto-generated receipt for a completed transaction. Available to both
// operator and customer the moment the transaction's status flips to filled
// (or Cedar reports COMPLETED / payout ARRIVED). Independent of Cedar's MT103 —
// the MT103 is a separate bank-confirmation doc that gets uploaded into the
// transaction's supporting documents once the operator has it.

function buildTransactionConfirmationPage(doc, q, operatorName) {
  drawHeader(doc, "Transaction Confirmation");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Confirmation", MARGIN, y);

  doc.setFont("courier", "normal");
  doc.setFontSize(11);
  doc.setTextColor(MUTED);
  doc.text(ref(q.id), PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(`Status: COMPLETED · Issued ${fmtDateTime(q.filled_at || q.cedar_request_status_updated_at || q.created_at)}`, MARGIN, y);
  y += 12;

  // Big amount card
  doc.setFillColor(INK);
  doc.roundedRect(MARGIN, y, CONTENT_W, 38, 3, 3, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(LIME);
  doc.text("AMOUNT PROCESSED", MARGIN + 8, y + 9);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(PAPER);
  doc.text(fmtMoney(q.amount, q.currency || "USD"), MARGIN + 8, y + 24);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor(LIME);
  doc.text(`Customer paid  ${fmtNgn(q.ngn_total)}  @  ₦${parseFloat(q.rate || 0).toFixed(2)}/$`, MARGIN + 8, y + 33);
  y += 48;

  // Parties
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Parties", MARGIN, y);
  y += 6;

  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Customer", q.customer_name || "—", MARGIN, y);
  drawLabelValue(doc, "Recipient / supplier", q.beneficiary || "—", MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text([q.customer_phone, q.customer?.email].filter(Boolean).join("  ·  ") || "—", MARGIN, y + 11);
  doc.text(q.destination || "—", MARGIN + colW + 8, y + 11);
  y += 20;

  drawLabelValue(doc, "Issued by", operatorName || q.bdc_name || "Operator", MARGIN, y);
  drawLabelValue(doc, "Settled via", "Licensed payment partner", MARGIN + colW + 8, y);
  y += 16;

  // Transaction details table
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Transaction details", MARGIN, y);
  y += 7;

  const rows = [
    ["Reference", ref(q.id)],
    ["Amount", `${fmtMoney(q.amount, q.currency || "USD")}`],
    ["Customer rate", `₦${parseFloat(q.rate || 0).toFixed(2)} / $`],
    ["Customer paid (NGN)", fmtNgn(q.ngn_total)],
    ["Purpose", q.cedar_purpose || "GOODS_PURCHASED"],
    ["Status", "COMPLETED"],
    ["Completed at", fmtDateTime(q.filled_at || q.cedar_request_status_updated_at)],
  ];
  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(label.toUpperCase(), MARGIN, y);
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });
    doc.setDrawColor(LINE);
    doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
    y += 9;
  });

  // Bank details (if present from Cedar response)
  const bank = q.cedar_bank_details || {};
  const bankName = bank.bank_name || bank.bankName;
  if (bankName) {
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(INK);
    doc.text("Settlement route", MARGIN, y);
    y += 7;
    const bankRows = [
      ["Bank", bankName],
      ["Account name", bank.account_name || bank.accountName || "—"],
      ["Account number", bank.account_number || bank.accountNumber || "—"],
      ["Reference", ref(q.id)],
    ];
    bankRows.forEach(([label, value]) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text(label.toUpperCase(), MARGIN, y);
      doc.setFont("courier", "normal");
      doc.setFontSize(10);
      doc.setTextColor(INK);
      doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });
      doc.setDrawColor(LINE);
      doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
      y += 9;
    });
  }

  // Footer note
  const noteY = PAGE_H - 35;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("This confirmation is generated automatically by XaePay when a cross-border trade payment completes. The MT103 / SWIFT wire confirmation is a separate document issued by the licensed payment partner; once available it will be attached to this transaction.", MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Powered by XaePay · Software/compliance layer · Funds custody by licensed payment partner.", MARGIN, noteY + 17, { maxWidth: CONTENT_W });
}

export function generateTransactionConfirmationPdf({ quote, operatorName }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildTransactionConfirmationPage(doc, quote, operatorName);
  drawFooter(doc, 1, 1);
  return doc;
}

export function downloadTransactionConfirmationPdf(doc, quote) {
  doc.save(`${ref(quote.id)}-confirmation-XaePay.pdf`);
}

export function downloadCompliancePackPdf(doc, customer) {
  const safeName = (customer?.name || "Customer").replace(/[^\w]+/g, "_");
  const period = new Date().toLocaleDateString("en-GB", { month: "short", year: "numeric" }).replace(/\s+/g, "_");
  doc.save(`${safeName}_compliance_pack_${period}.pdf`);
}

// === Invoice PDF =============================================================
// Operator-issued invoice for goods or services rendered. Customer reviews +
// hits "Pay this invoice" in their portal, which kicks off the existing
// rate-quote flow with the invoice's amount + currency prefilled. PDF is
// downloadable + emailable.

// Add a brand logo to the PDF header. jsPDF needs a data URL; we fetch the
// public URL, convert to data URL, then addImage. Returns true if the logo
// was actually drawn, false otherwise. Safe to call even if no brand exists.
async function tryDrawBrandLogo(doc, brand, x, y) {
  if (!brand?.brand_logo_url) return false;
  try {
    const res = await fetch(brand.brand_logo_url);
    if (!res.ok) return false;
    const blob = await res.blob();
    const dataUrl = await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
    // Detect format from blob
    const fmt = (blob.type || "").includes("jpeg") || (blob.type || "").includes("jpg") ? "JPEG" : "PNG";
    doc.addImage(dataUrl, fmt, x, y, 18, 18);  // 18mm square
    return true;
  } catch {
    return false;
  }
}

function buildInvoicePdfPage(doc, invoice, items, brand) {
  // Only business-mode operators with a populated brand get the branded header.
  // Individual operators (and businesses that haven't set a brand) get the
  // default XaePay-tinted header.
  const branded = brand && brand.operator_type === "business" && (brand.business_name || brand.brand_logo_url);
  const accent = branded && brand.brand_accent_color ? brand.brand_accent_color : INK;

  drawHeader(doc, "Invoice", accent);

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Invoice", MARGIN, y);

  doc.setFont("courier", "normal");
  doc.setFontSize(12);
  doc.setTextColor(MUTED);
  doc.text(invoice.invoice_number || "—", PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  const issued = invoice.issue_date ? fmtDate(invoice.issue_date) : fmtDate(invoice.created_at);
  const due = invoice.due_date ? `· Due ${fmtDate(invoice.due_date)}` : "";
  doc.text(`Issued ${issued} ${due}`, MARGIN, y);
  y += 14;

  // Issued by / Bill to
  const colW = (CONTENT_W - 8) / 2;
  const issuerName = branded && brand.business_name ? brand.business_name : (invoice.operator_name || "Operator");
  drawLabelValue(doc, "Issued by", issuerName, MARGIN, y);
  drawLabelValue(doc, "Bill to", invoice.customer_name || "Customer", MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  // For business operators, show their business contact line; for everyone
  // else, the legacy "Via XaePay" tag goes here. Either way the footer keeps
  // the "Issued via XaePay" compliance line.
  const issuerContact = branded
    ? [brand.business_phone, brand.business_email, brand.business_address].filter(Boolean).join("  ·  ")
    : "Via XaePay";
  doc.text(issuerContact || "Via XaePay", MARGIN, y + 11, { maxWidth: colW });
  doc.text([invoice.customer_phone, invoice.customer_email].filter(Boolean).join("  ·  ") || "—", MARGIN + colW + 8, y + 11, { maxWidth: colW });
  y += 22;

  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  // Items table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("DESCRIPTION", MARGIN, y);
  doc.text("QTY", MARGIN + 105, y, { align: "right" });
  doc.text("UNIT", MARGIN + 135, y, { align: "right" });
  doc.text("AMOUNT", PAGE_W - MARGIN, y, { align: "right" });
  y += 5;
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 7;

  const ccy = invoice.currency || "USD";
  const sortedItems = [...(items || [])].sort((a, b) => (a.position || 0) - (b.position || 0));
  sortedItems.forEach((it) => {
    if (y > PAGE_H - 80) {
      drawFooter(doc, doc.internal.getNumberOfPages(), 0);
      doc.addPage();
      drawHeader(doc, "Invoice (cont.)");
      y = 38;
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    const descLines = doc.splitTextToSize(it.description || "—", 95);
    doc.text(descLines, MARGIN, y);

    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    doc.text(String(parseFloat(it.quantity || 1)), MARGIN + 105, y, { align: "right" });
    doc.text(fmtMoney(parseFloat(it.unit_price || 0), ccy), MARGIN + 135, y, { align: "right" });
    doc.setFont("courier", "bold");
    doc.text(fmtMoney(parseFloat(it.amount || 0), ccy), PAGE_W - MARGIN, y, { align: "right" });

    y += Math.max(descLines.length * 4, 6) + 4;
  });

  // Totals
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  const sumX = PAGE_W - MARGIN - 60;
  const sumRow = (label, value, bold) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(bold ? 12 : 9);
    doc.setTextColor(INK);
    doc.text(label, sumX, y);
    doc.setFont("courier", bold ? "bold" : "normal");
    doc.text(value, PAGE_W - MARGIN, y, { align: "right" });
    y += bold ? 8 : 6;
  };

  sumRow("Subtotal", fmtMoney(parseFloat(invoice.subtotal || 0), ccy));
  if (parseFloat(invoice.tax || 0) > 0) {
    sumRow("Tax", fmtMoney(parseFloat(invoice.tax || 0), ccy));
  }
  y += 2;
  doc.setDrawColor(INK);
  doc.line(sumX, y, PAGE_W - MARGIN, y);
  y += 6;
  sumRow(`Total (${ccy})`, fmtMoney(parseFloat(invoice.total || 0), ccy), true);

  // Payment methods (operator-configured per-invoice instructions)
  const methods = Array.isArray(invoice.payment_methods) ? invoice.payment_methods : [];
  if (methods.length > 0) {
    y += 6;
    if (y > PAGE_H - 60) { drawFooter(doc, doc.internal.getNumberOfPages(), 0); doc.addPage(); drawHeader(doc, "Invoice (cont.)"); y = 38; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text("Payment options", MARGIN, y);
    y += 6;
    const TYPE_LABELS = {
      zelle: "Zelle", ach: "ACH transfer", wire_us: "Domestic wire (US)", apple_pay: "Apple Pay / Cash App",
      check: "Certified check", card_link: "Card payment link", bank_ngn: "Nigerian bank transfer",
      ussd: "USSD", crossborder: "International (XaePay)", other: "Other",
    };
    methods.forEach((m) => {
      if (y > PAGE_H - 50) { drawFooter(doc, doc.internal.getNumberOfPages(), 0); doc.addPage(); drawHeader(doc, "Invoice (cont.)"); y = 38; }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(INK);
      const label = (TYPE_LABELS[m.type] || m.type) + (m.label ? ` · ${m.label}` : "");
      doc.text(label, MARGIN, y);
      y += 4.5;
      if (m.instructions) {
        doc.setFont("courier", "normal");
        doc.setFontSize(8.5);
        doc.setTextColor(MUTED);
        const lines = doc.splitTextToSize(m.instructions, CONTENT_W);
        doc.text(lines, MARGIN, y);
        y += lines.length * 4 + 2;
      } else if (m.type === "crossborder") {
        doc.setFont("helvetica", "italic");
        doc.setFontSize(8.5);
        doc.setTextColor(MUTED);
        doc.text("Pay via cross-border rate quote in your XaePay portal.", MARGIN, y);
        y += 4 + 2;
      }
      y += 2;
    });
  }

  // Notes
  if (invoice.notes) {
    y += 6;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text("Notes", MARGIN, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    const noteLines = doc.splitTextToSize(invoice.notes, CONTENT_W);
    doc.text(noteLines, MARGIN, y);
    y += noteLines.length * 4.5 + 4;
  }

  // Status pill (if not draft)
  if (invoice.status && invoice.status !== "draft") {
    const pillBg = invoice.status === "paid" ? "#d1fae5" : invoice.status === "void" ? "#fee2e2" : "#fef3c7";
    const pillColor = invoice.status === "paid" ? "#065f46" : invoice.status === "void" ? "#991b1b" : "#92400e";
    doc.setFillColor(pillBg);
    doc.roundedRect(MARGIN, y, 30, 7, 2, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(pillColor);
    doc.text(invoice.status.toUpperCase(), MARGIN + 15, y + 4.7, { align: "center" });
  }

  // Footer
  const noteY = PAGE_H - 30;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`Pay using any of the payment options above, then confirm the payment in your XaePay customer portal. The operator who issued this invoice will verify receipt before the invoice is marked paid.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Issued via XaePay · Operator-issued invoice · XaePay does not custody local-rail payments.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateInvoicePdf({ invoice, items, brand }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildInvoicePdfPage(doc, invoice, items, brand);
  drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  return doc;
}

export function downloadInvoicePdf(doc, invoice) {
  const num = (invoice?.invoice_number || "invoice").replace(/[^\w-]+/g, "_");
  doc.save(`${num}-XaePay.pdf`);
}

// =============================================================================
// Proforma restructured invoice PDF.
// Restructures the original supplier invoice into a new formal invoice
// where the OPERATOR is the buyer of record and the END CUSTOMER is the
// consignee + ultimate beneficial owner. Preserves the original supplier
// + line items + total + currency exactly. References the original
// invoice number for the audit trail.
// =============================================================================

function buildProformaRestructuredPage(doc, args) {
  const { supplier, buyer, consignee, lineItems, totals, originalInvoice, formMResponsibility, operatorName } = args;
  const MARGIN_L = 18;
  const PAGE_W = 210;
  let y = 22;

  // Top bar with "RESTRUCTURED" stamp
  doc.setFillColor(INK);
  doc.rect(0, 0, PAGE_W, 12, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor("#c5f24a");
  doc.text("RESTRUCTURED · THIRD-PARTY TRADE", MARGIN_L, 7.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor("#ffffff");
  doc.text(`Original: ${originalInvoice?.invoice_number || "—"}`, PAGE_W - MARGIN_L, 7.5, { align: "right" });

  y = 22;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(INK);
  doc.text("Invoice", MARGIN_L, y);
  doc.setFont("courier", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(originalInvoice?.invoice_number ? `REF/${originalInvoice.invoice_number}` : "—", PAGE_W - MARGIN_L, y, { align: "right" });
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`Restructured ${fmtDate(new Date().toISOString())} · Buyer-of-record substitution per trade-partner agreement`, MARGIN_L, y);
  y += 12;

  // Three-column parties block
  const colW = (PAGE_W - 2 * MARGIN_L - 8) / 3;
  const drawParty = (label, name, address, contact, taxId, accentColor) => (x) => {
    doc.setDrawColor(LINE);
    doc.setFillColor("#fafaf8");
    doc.roundedRect(x, y, colW, 50, 2, 2, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(accentColor || EMERALD);
    doc.text(label.toUpperCase(), x + 4, y + 6);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text(String(name || "—").slice(0, 35), x + 4, y + 13);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    if (address) doc.text(String(address).slice(0, 80), x + 4, y + 19, { maxWidth: colW - 8 });
    if (contact) doc.text(String(contact).slice(0, 50), x + 4, y + 34, { maxWidth: colW - 8 });
    if (taxId) doc.text(`Tax ID: ${String(taxId).slice(0, 30)}`, x + 4, y + 42, { maxWidth: colW - 8 });
  };
  drawParty("Supplier", supplier?.name, supplier?.address, supplier?.contact, supplier?.tax_id)(MARGIN_L);
  drawParty("Buyer (Trade Partner)", buyer?.name || operatorName, buyer?.address, buyer?.contact, buyer?.tax_id, INK)(MARGIN_L + colW + 4);
  drawParty("Consignee / UBO", consignee?.name, consignee?.address, consignee?.contact, consignee?.tax_id)(MARGIN_L + 2 * (colW + 4));
  y += 56;

  // Line items table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("DESCRIPTION", MARGIN_L, y);
  doc.text("QTY", PAGE_W - MARGIN_L - 60, y, { align: "right" });
  doc.text("UNIT", PAGE_W - MARGIN_L - 35, y, { align: "right" });
  doc.text("AMOUNT", PAGE_W - MARGIN_L, y, { align: "right" });
  y += 2;
  doc.setDrawColor(LINE);
  doc.line(MARGIN_L, y, PAGE_W - MARGIN_L, y);
  y += 5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(INK);
  (lineItems || []).forEach((it) => {
    if (y > 250) {
      doc.addPage();
      y = 25;
    }
    doc.text(String(it.description || "—").slice(0, 70), MARGIN_L, y, { maxWidth: PAGE_W - MARGIN_L - 70 });
    doc.setFont("courier", "normal");
    doc.text(String(it.quantity ?? "—"), PAGE_W - MARGIN_L - 60, y, { align: "right" });
    doc.text(String(it.unit_price != null ? fmtMoney(it.unit_price, totals?.currency) : "—"), PAGE_W - MARGIN_L - 35, y, { align: "right" });
    doc.text(String(it.amount != null ? fmtMoney(it.amount, totals?.currency) : "—"), PAGE_W - MARGIN_L, y, { align: "right" });
    doc.setFont("helvetica", "normal");
    y += 6;
  });

  y += 4;
  doc.setDrawColor(LINE);
  doc.line(PAGE_W - MARGIN_L - 70, y, PAGE_W - MARGIN_L, y);
  y += 6;

  // Totals
  const totalRow = (label, value, bold) => {
    doc.setFont(bold ? "helvetica" : "helvetica", bold ? "bold" : "normal");
    doc.setFontSize(bold ? 11 : 9);
    doc.setTextColor(bold ? INK : MUTED);
    doc.text(label, PAGE_W - MARGIN_L - 40, y);
    doc.setFont("courier", bold ? "bold" : "normal");
    doc.text(String(value), PAGE_W - MARGIN_L, y, { align: "right" });
    y += bold ? 7 : 5;
  };
  if (totals?.subtotal != null) totalRow("Subtotal", fmtMoney(totals.subtotal, totals?.currency));
  if (totals?.tax != null) totalRow("Tax", fmtMoney(totals.tax, totals?.currency));
  if (totals?.shipping != null) totalRow("Shipping", fmtMoney(totals.shipping, totals?.currency));
  totalRow("TOTAL", fmtMoney(totals?.total ?? 0, totals?.currency), true);

  y += 4;

  // Footer block — disclosures
  if (y > 230) { doc.addPage(); y = 25; }
  doc.setDrawColor(LINE);
  doc.line(MARGIN_L, y, PAGE_W - MARGIN_L, y);
  y += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(INK);
  doc.text("Disclosures", MARGIN_L, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  const discText = `This is a restructured invoice. The original supplier invoice (ref ${originalInvoice?.invoice_number || "—"}, dated ${originalInvoice?.invoice_date ? fmtDate(originalInvoice.invoice_date) : "—"}) named ${originalInvoice?.bill_to_name || "the consignee"} as the buyer. ${buyer?.name || operatorName} is acting as contractual trade-partner buyer on behalf of ${consignee?.name || "the consignee"}, who is the ultimate beneficial owner of the goods. Both parties have executed a trade-partner attestation prior to this restructure.`;
  doc.text(discText, MARGIN_L, y, { maxWidth: PAGE_W - 2 * MARGIN_L });
  y += 22;
  if (originalInvoice?.payment_terms) {
    doc.text(`Payment terms: ${originalInvoice.payment_terms}`, MARGIN_L, y);
    y += 5;
  }
  if (originalInvoice?.incoterms) {
    doc.text(`Incoterms: ${originalInvoice.incoterms}`, MARGIN_L, y);
    y += 5;
  }
  if (formMResponsibility) {
    const fmLabel = formMResponsibility === "operator" ? `${buyer?.name || operatorName} (operator) opens Form M` : formMResponsibility === "customer" ? `${consignee?.name || "Consignee"} (end customer) opens Form M` : "Form M not applicable";
    doc.text(`Form M: ${fmLabel}`, MARGIN_L, y);
    y += 5;
  }
  if (originalInvoice?.bank_details) {
    y += 3;
    doc.setFont("helvetica", "bold");
    doc.text("Supplier bank details (as on original)", MARGIN_L, y);
    y += 4;
    doc.setFont("helvetica", "normal");
    doc.text(String(originalInvoice.bank_details).slice(0, 400), MARGIN_L, y, { maxWidth: PAGE_W - 2 * MARGIN_L });
  }
}

export function generateProformaRestructuredPdf(args) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildProformaRestructuredPage(doc, args);
  drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  return doc;
}

export function downloadProformaRestructuredPdf(doc, quote) {
  const ref = (quote?.id || "quote").slice(0, 8).toUpperCase();
  doc.save(`Restructured-${ref}-XaePay.pdf`);
}

// =============================================================================
// Receipt — auto-generated when an invoice is marked paid. Acts as the
// operator's proof-of-receipt to the customer. Receipt number is derived from
// the invoice number (INV-XXXX → INV-XXXX/R) so we don't need a new sequence.
// `payment` is the confirmed invoice_payments row (or a synthesized object for
// cross-border quotes that auto-pay through the Cedar trigger).
// =============================================================================

const RECEIPT_METHOD_LABELS = {
  zelle: "Zelle", ach: "ACH transfer", wire_us: "Domestic wire (US)", apple_pay: "Apple Pay / Cash App",
  check: "Certified check", card_link: "Card payment", bank_ngn: "Nigerian bank transfer",
  ussd: "USSD", crossborder: "International (XaePay)", other: "Other",
};

function buildReceiptPdfPage(doc, invoice, items, payment) {
  drawHeader(doc, "Receipt");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Receipt", MARGIN, y);

  const receiptNum = `${invoice.invoice_number || "INV"}/R`;
  doc.setFont("courier", "normal");
  doc.setFontSize(12);
  doc.setTextColor(MUTED);
  doc.text(receiptNum, PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  const issuedAt = invoice.receipt_issued_at || invoice.paid_at || new Date().toISOString();
  doc.text(`Issued ${fmtDateTime(issuedAt)}`, MARGIN, y);
  y += 14;

  // Big paid amount stripe
  const ccy = invoice.currency || payment?.currency || "USD";
  const paidAmt = parseFloat(payment?.amount || invoice.total || 0);
  doc.setFillColor(EMERALD);
  doc.roundedRect(MARGIN, y, CONTENT_W, 26, 3, 3, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#d1fae5");
  doc.text("AMOUNT RECEIVED", MARGIN + 6, y + 8);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor("#ffffff");
  doc.text(fmtMoney(paidAmt, ccy), MARGIN + 6, y + 19);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor("#d1fae5");
  doc.text(`PAID · ${fmtDate(invoice.paid_at || issuedAt)}`, PAGE_W - MARGIN - 6, y + 19, { align: "right" });
  y += 34;

  // Issued by / Issued to
  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Received from", invoice.customer_name || "Customer", MARGIN, y);
  drawLabelValue(doc, "Received by", invoice.operator_name || "Operator", MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text([invoice.customer_phone, invoice.customer_email].filter(Boolean).join("  ·  ") || "—", MARGIN, y + 11, { maxWidth: colW });
  doc.text("Via XaePay", MARGIN + colW + 8, y + 11);
  y += 22;

  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  // Payment details
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text("Payment details", MARGIN, y);
  y += 7;
  const methodLabel = payment?.method_type ? (RECEIPT_METHOD_LABELS[payment.method_type] || payment.method_type) : "—";
  const detailRow = (label, value) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text(label, MARGIN, y);
    doc.setFont("courier", "normal");
    doc.setTextColor(INK);
    doc.text(value || "—", PAGE_W - MARGIN, y, { align: "right" });
    y += 6;
  };
  detailRow("Method", methodLabel + (payment?.method_label ? ` · ${payment.method_label}` : ""));
  if (payment?.reference) detailRow("Reference", payment.reference);
  detailRow("Invoice", invoice.invoice_number || "—");
  if (invoice.issue_date) detailRow("Invoice issued", fmtDate(invoice.issue_date));
  detailRow("Payment confirmed", fmtDateTime(invoice.paid_at || issuedAt));
  y += 4;

  // Itemized recap so the receipt is self-contained
  if (Array.isArray(items) && items.length > 0) {
    doc.setDrawColor(LINE);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text("What this covers", MARGIN, y);
    y += 7;
    const sortedItems = [...items].sort((a, b) => (a.position || 0) - (b.position || 0));
    sortedItems.forEach((it) => {
      if (y > PAGE_H - 50) { drawFooter(doc, doc.internal.getNumberOfPages(), 0); doc.addPage(); drawHeader(doc, "Receipt (cont.)"); y = 38; }
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(INK);
      const descLines = doc.splitTextToSize(it.description || "—", CONTENT_W - 40);
      doc.text(descLines, MARGIN, y);
      doc.setFont("courier", "bold");
      doc.setFontSize(9);
      doc.text(fmtMoney(parseFloat(it.amount || 0), ccy), PAGE_W - MARGIN, y, { align: "right" });
      y += Math.max(descLines.length * 4, 6) + 2;
    });
  }

  // Status confirmation
  y += 4;
  doc.setFillColor("#d1fae5");
  doc.roundedRect(MARGIN, y, 36, 7, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor("#065f46");
  doc.text("RECEIPT ISSUED", MARGIN + 18, y + 4.7, { align: "center" });

  // Footer
  const noteY = PAGE_H - 30;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`This receipt acknowledges that ${invoice.operator_name || "the operator"} has received payment for invoice ${invoice.invoice_number || ""}. Keep this document for your records.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Issued via XaePay · Operator-confirmed receipt · Not a tax document.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateReceiptPdf({ invoice, items, payment }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildReceiptPdfPage(doc, invoice, items, payment);
  drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  return doc;
}

export function downloadReceiptPdf(doc, invoice) {
  const num = (invoice?.invoice_number || "receipt").replace(/[^\w-]+/g, "_");
  doc.save(`${num}-R-XaePay.pdf`);
}

// =============================================================================
// Recipient receipt — operator-issued confirmation that a payout was sent to a
// recipient. Distinct from the invoice receipt (which acknowledges money
// received from a customer). Triggered when a quote moves into a completed
// state (status=filled / cedar COMPLETED / cedar ARRIVED).
// =============================================================================

function buildRecipientReceiptPage(doc, quote, recipient) {
  drawHeader(doc, "Payment Confirmation");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Payment sent", MARGIN, y);

  const ref = `QU-${(quote.id || "").slice(0, 8).toUpperCase()}/R`;
  doc.setFont("courier", "normal");
  doc.setFontSize(12);
  doc.setTextColor(MUTED);
  doc.text(ref, PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  const issuedAt = quote.recipient_receipt_issued_at || quote.cedar_request_status_updated_at || new Date().toISOString();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(`Issued ${fmtDateTime(issuedAt)}`, MARGIN, y);
  y += 14;

  // Amount stripe
  const ccy = quote.currency || "USD";
  const amt = parseFloat(quote.amount || 0);
  doc.setFillColor(EMERALD);
  doc.roundedRect(MARGIN, y, CONTENT_W, 26, 3, 3, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#d1fae5");
  doc.text("AMOUNT SENT TO YOU", MARGIN + 6, y + 8);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor("#ffffff");
  doc.text(fmtMoney(amt, ccy), MARGIN + 6, y + 19);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor("#d1fae5");
  doc.text(`PAID · ${fmtDate(issuedAt)}`, PAGE_W - MARGIN - 6, y + 19, { align: "right" });
  y += 34;

  // From / To columns
  const colW = (CONTENT_W - 8) / 2;
  const recipientName = recipient?.full_name || recipient?.legal_business_name || quote.beneficiary || "Recipient";
  const senderName = quote.customer_name || "Customer";
  const operatorName = quote.bdc_name || "XaeccoX";
  drawLabelValue(doc, "Paid by", senderName, MARGIN, y);
  drawLabelValue(doc, "Paid to", recipientName, MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`via ${operatorName} (XaePay)`, MARGIN, y + 11);
  if (recipient?.bank_name || recipient?.bank_account_number) {
    const bankLine = [recipient.bank_name, recipient.bank_account_number ? `· ${recipient.bank_account_number.slice(-4).padStart(recipient.bank_account_number.length, "•")}` : ""].filter(Boolean).join(" ");
    doc.text(bankLine, MARGIN + colW + 8, y + 11, { maxWidth: colW });
  }
  y += 22;

  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  // Payment details
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text("Payment details", MARGIN, y);
  y += 7;

  const detailRow = (label, value) => {
    if (!value) return;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text(label, MARGIN, y);
    doc.setFont("courier", "normal");
    doc.setTextColor(INK);
    const lines = doc.splitTextToSize(String(value), CONTENT_W - 70);
    doc.text(lines, PAGE_W - MARGIN, y, { align: "right" });
    y += Math.max(lines.length * 5, 6);
  };
  detailRow("Reference", ref);
  detailRow("Transaction ID", quote.id || null);
  if (quote.cedar_business_request_id) detailRow("Partner reference", quote.cedar_business_request_id);
  detailRow("Sender", senderName);
  detailRow("Recipient", recipientName);
  if (recipient?.bank_name) detailRow("Bank", recipient.bank_name);
  if (recipient?.bank_account_number) detailRow("Account", recipient.bank_account_number);
  if (quote.purpose_note) detailRow("Purpose", quote.purpose_note);
  detailRow("Settled", fmtDateTime(issuedAt));
  y += 6;

  // Status pill
  doc.setFillColor("#d1fae5");
  doc.roundedRect(MARGIN, y, 36, 7, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor("#065f46");
  doc.text("PAYMENT SETTLED", MARGIN + 18, y + 4.7, { align: "center" });

  // Footer
  const noteY = PAGE_H - 30;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`This confirms that ${senderName} has sent the amount above to ${recipientName} via ${operatorName} on XaePay. Keep this document for your records.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Issued via XaePay · Operator-confirmed payout · Not a tax document.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateRecipientReceiptPdf({ quote, recipient }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildRecipientReceiptPage(doc, quote, recipient || {});
  drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  return doc;
}

export function downloadRecipientReceiptPdf(doc, quote) {
  const id = (quote?.id || "receipt").slice(0, 8);
  doc.save(`payout-${id}-R-XaePay.pdf`);
}

// =============================================================================
// Regulatory reports — monthly transaction summary, quarterly customer
// activity, suspicious-transaction draft. Each report renders as a structured
// PDF that operators can hand to their compliance officer / regulator.
// =============================================================================

function buildMonthlyTransactionReportPage(doc, { operator, transactions, period, summary }) {
  drawHeader(doc, "Transaction Report");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Transaction Report", MARGIN, y);

  doc.setFont("courier", "normal");
  doc.setFontSize(11);
  doc.setTextColor(MUTED);
  doc.text(period.label || "Period", PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(`Operator: ${operator?.name || "—"}`, MARGIN, y);
  y += 4;
  doc.text(`Generated: ${fmtDateTime(new Date().toISOString())}`, MARGIN, y);
  y += 4;
  doc.text(`Coverage: ${fmtDate(period.start)} → ${fmtDate(period.end)}`, MARGIN, y);
  y += 14;

  // Summary box
  doc.setFillColor(EMERALD);
  doc.roundedRect(MARGIN, y, CONTENT_W, 26, 3, 3, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#d1fae5");
  doc.text("SUMMARY", MARGIN + 6, y + 8);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor("#ffffff");
  const summaryText = `${summary.totalCount} transactions · ${summary.totalVolumeText}`;
  doc.text(summaryText, MARGIN + 6, y + 18);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor("#d1fae5");
  doc.text(`${summary.settledCount} settled · ${summary.pendingCount} pending`, PAGE_W - MARGIN - 6, y + 18, { align: "right" });
  y += 34;

  // Volume breakdown by currency
  if (summary.volumesByCurrency && Object.keys(summary.volumesByCurrency).length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text("Volume by currency", MARGIN, y);
    y += 6;
    Object.entries(summary.volumesByCurrency).forEach(([ccy, vol]) => {
      doc.setFont("courier", "normal");
      doc.setFontSize(9);
      doc.setTextColor(MUTED);
      doc.text(ccy, MARGIN, y);
      doc.setTextColor(INK);
      doc.text(fmtMoney(vol, ccy), PAGE_W - MARGIN, y, { align: "right" });
      y += 5;
    });
    y += 6;
  }

  // Transactions table
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text("Transactions", MARGIN, y);
  y += 6;

  // Column headers
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(MUTED);
  doc.text("DATE", MARGIN, y);
  doc.text("CUSTOMER", MARGIN + 24, y);
  doc.text("BENEFICIARY", MARGIN + 75, y);
  doc.text("DEST", MARGIN + 125, y);
  doc.text("AMOUNT", MARGIN + 145, y, { align: "right" });
  doc.text("STATUS", PAGE_W - MARGIN, y, { align: "right" });
  y += 3;
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 5;

  // Rows
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(INK);
  transactions.forEach((t) => {
    if (y > PAGE_H - 30) {
      drawFooter(doc, doc.internal.getNumberOfPages(), 0);
      doc.addPage();
      drawHeader(doc, "Transaction Report (cont.)");
      y = 38;
    }
    const dateStr = t.created_at ? new Date(t.created_at).toLocaleDateString("en-GB", { day: "2-digit", month: "short" }) : "—";
    doc.setTextColor(MUTED);
    doc.setFont("courier", "normal");
    doc.text(dateStr, MARGIN, y);
    doc.setTextColor(INK);
    doc.setFont("helvetica", "normal");
    const cust = (t.customer_name || "—").slice(0, 22);
    doc.text(cust, MARGIN + 24, y);
    const ben = (t.beneficiary || "—").slice(0, 22);
    doc.text(ben, MARGIN + 75, y);
    doc.setFont("courier", "normal");
    doc.text((t.destination || "—").slice(0, 6), MARGIN + 125, y);
    doc.text(`${t.currency} ${parseFloat(t.amount || 0).toLocaleString(undefined, { maximumFractionDigits: 0 })}`, MARGIN + 145, y, { align: "right" });
    const status = ((t.cedar_request_status || "").toUpperCase().includes("COMPLETED") || t.status === "filled") ? "SETTLED" : (t.status || "—").toUpperCase().slice(0, 10);
    doc.setTextColor(status === "SETTLED" ? EMERALD : MUTED);
    doc.text(status, PAGE_W - MARGIN, y, { align: "right" });
    y += 5;
  });

  // Footer
  const noteY = PAGE_H - 24;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(MUTED);
  doc.text(`This report was generated by XaePay on behalf of ${operator?.name || "the operator"} from their transaction records. It is intended as a starting point for compliance filings (CBN, SCUML, NFIU, FIRS). The operator is responsible for verifying accuracy and adapting format to specific regulatory requirements.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("XaePay is not a regulated entity; this report does not constitute a regulatory filing.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateMonthlyTransactionReportPdf(args) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildMonthlyTransactionReportPage(doc, args);
  drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  return doc;
}

export function downloadRegulatoryReportPdf(doc, type, periodLabel) {
  const safePeriod = (periodLabel || "report").replace(/[^\w-]+/g, "_");
  const safeType = (type || "regulatory").replace(/[^\w-]+/g, "_");
  doc.save(`XaePay-${safeType}-${safePeriod}.pdf`);
}

// =============================================================================
// Quarterly Customer Activity Report — for CBN / SCUML AML obligations.
// One row per customer who transacted in the quarter, with KYC status, count,
// volume per currency, and first/last transaction dates.
// =============================================================================

function buildQuarterlyCustomerActivityReportPage(doc, { operator, rows, period, summary }) {
  drawHeader(doc, "Customer Activity");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Customer Activity", MARGIN, y);

  doc.setFont("courier", "normal");
  doc.setFontSize(11);
  doc.setTextColor(MUTED);
  doc.text(period.label || "Quarter", PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(`Operator: ${operator?.name || "—"}`, MARGIN, y);
  y += 4;
  doc.text(`Generated: ${fmtDateTime(new Date().toISOString())}`, MARGIN, y);
  y += 4;
  doc.text(`Coverage: ${fmtDate(period.start)} → ${fmtDate(period.end)}`, MARGIN, y);
  y += 14;

  // Summary box
  doc.setFillColor(EMERALD);
  doc.roundedRect(MARGIN, y, CONTENT_W, 26, 3, 3, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#d1fae5");
  doc.text("SUMMARY", MARGIN + 6, y + 8);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor("#ffffff");
  doc.text(`${summary.customerCount} active customers · ${summary.txnCount} transactions`, MARGIN + 6, y + 18);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor("#d1fae5");
  doc.text(summary.totalVolumeText || "", PAGE_W - MARGIN - 6, y + 18, { align: "right" });
  y += 34;

  // KYC status breakdown
  if (summary.kycBreakdown && Object.keys(summary.kycBreakdown).length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text("KYC status across active customers", MARGIN, y);
    y += 6;
    Object.entries(summary.kycBreakdown).forEach(([status, count]) => {
      doc.setFont("courier", "normal");
      doc.setFontSize(9);
      doc.setTextColor(MUTED);
      doc.text(status, MARGIN, y);
      doc.setTextColor(INK);
      doc.text(`${count}`, PAGE_W - MARGIN, y, { align: "right" });
      y += 5;
    });
    y += 6;
  }

  // Customer table
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text("Active customers", MARGIN, y);
  y += 6;

  // Headers
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(MUTED);
  doc.text("CUSTOMER", MARGIN, y);
  doc.text("TYPE", MARGIN + 65, y);
  doc.text("KYC", MARGIN + 82, y);
  doc.text("TXNS", MARGIN + 105, y, { align: "right" });
  doc.text("VOLUME", PAGE_W - MARGIN, y, { align: "right" });
  y += 3;
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(INK);
  rows.forEach((r) => {
    if (y > PAGE_H - 30) {
      drawFooter(doc, doc.internal.getNumberOfPages(), 0);
      doc.addPage();
      drawHeader(doc, "Customer Activity (cont.)");
      y = 38;
    }
    const nameLine = (r.business_name || r.name || "—").slice(0, 30);
    doc.setTextColor(INK);
    doc.setFont("helvetica", "normal");
    doc.text(nameLine, MARGIN, y);

    doc.setFont("courier", "normal");
    doc.setTextColor(MUTED);
    doc.text((r.type || "—").slice(0, 8), MARGIN + 65, y);
    const kyc = (r.kyc_status || "—").toUpperCase().slice(0, 12);
    const kycColor = kyc === "VALID" || kyc === "APPROVED" ? EMERALD : MUTED;
    doc.setTextColor(kycColor);
    doc.text(kyc, MARGIN + 82, y);

    doc.setTextColor(INK);
    doc.text(`${r.txnCount}`, MARGIN + 105, y, { align: "right" });

    doc.setFont("courier", "normal");
    doc.setTextColor(INK);
    doc.text(r.volumeText || "—", PAGE_W - MARGIN, y, { align: "right" });
    y += 5;

    // Secondary line: phone + email + first/last txn date
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(MUTED);
    const meta = [r.phone, r.email, r.firstTxn ? `first ${fmtDate(r.firstTxn)}` : null, r.lastTxn ? `last ${fmtDate(r.lastTxn)}` : null].filter(Boolean).join(" · ");
    doc.text(meta.slice(0, 110), MARGIN, y);
    doc.setFontSize(8);
    y += 5;
  });

  // Footer
  const noteY = PAGE_H - 24;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(MUTED);
  doc.text(`This report was generated by XaePay on behalf of ${operator?.name || "the operator"} from their customer + transaction records. Intended as a starting point for AML/KYC filings (CBN, SCUML, NFIU). The operator is responsible for verifying accuracy.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("XaePay is not a regulated entity; this report does not constitute a regulatory filing.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateQuarterlyCustomerActivityReportPdf(args) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildQuarterlyCustomerActivityReportPage(doc, args);
  drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  return doc;
}

// Build CSV from quarterly customer activity rows.
export function buildCustomerActivityCsv(rows) {
  const header = ["Customer", "Business name", "Type", "Phone", "Email", "KYC status", "KYC tier", "Provider KYC", "Transactions", "Volume (USD)", "Volume (GBP)", "Volume (EUR)", "Volume (NGN)", "First transaction", "Last transaction"];
  const csvRows = rows.map((r) => [
    r.name || "",
    r.business_name || "",
    r.type || "",
    r.phone || "",
    r.email || "",
    r.kyc_status || "",
    r.kyc_tier || "",
    r.provider_kyc_status || "",
    r.txnCount ?? 0,
    r.volumesByCurrency?.USD ?? "",
    r.volumesByCurrency?.GBP ?? "",
    r.volumesByCurrency?.EUR ?? "",
    r.volumesByCurrency?.NGN ?? "",
    r.firstTxn || "",
    r.lastTxn || "",
  ]);
  const escape = (v) => {
    const s = String(v ?? "");
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  return [header, ...csvRows].map((row) => row.map(escape).join(",")).join("\n");
}

// =============================================================================
// Suspicious Transaction Summary Report — pre-formatted for STR submission
// to CBN / NFIU / SCUML. Aggregates transactions flagged by AI compliance
// review + high-risk agent tasks for the period.
// =============================================================================

function buildSuspiciousTransactionReportPage(doc, { operator, period, flagged, summary }) {
  drawHeader(doc, "Suspicious Transaction Summary");

  let y = 38;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Suspicious Transaction Summary", MARGIN, y);
  doc.setFont("courier", "normal");
  doc.setFontSize(11);
  doc.setTextColor(MUTED);
  doc.text(period.label || "Period", PAGE_W - MARGIN, y, { align: "right" });
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(`Operator: ${operator?.name || "—"}`, MARGIN, y);
  y += 4;
  doc.text(`Generated: ${fmtDateTime(new Date().toISOString())}`, MARGIN, y);
  y += 4;
  doc.text(`Coverage: ${fmtDate(period.start)} → ${fmtDate(period.end)}`, MARGIN, y);
  y += 14;

  // Summary box — high contrast red/amber tone
  const summaryBg = summary.totalCount > 0 ? "#92400e" : EMERALD;
  doc.setFillColor(summaryBg);
  doc.roundedRect(MARGIN, y, CONTENT_W, 26, 3, 3, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#fef3c7");
  doc.text("SUMMARY", MARGIN + 6, y + 8);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor("#ffffff");
  doc.text(`${summary.totalCount} flagged transactions`, MARGIN + 6, y + 18);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor("#fef3c7");
  doc.text(summary.totalVolumeText || "", PAGE_W - MARGIN - 6, y + 18, { align: "right" });
  y += 34;

  // Reason breakdown
  if (summary.reasonBreakdown && Object.keys(summary.reasonBreakdown).length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text("Flag reasons", MARGIN, y);
    y += 6;
    Object.entries(summary.reasonBreakdown).forEach(([reason, count]) => {
      doc.setFont("courier", "normal");
      doc.setFontSize(9);
      doc.setTextColor(MUTED);
      doc.text(reason, MARGIN, y, { maxWidth: CONTENT_W - 20 });
      doc.setTextColor(INK);
      doc.text(`${count}`, PAGE_W - MARGIN, y, { align: "right" });
      y += 5;
    });
    y += 6;
  }

  // Per-transaction detail
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text("Flagged transactions", MARGIN, y);
  y += 6;

  if (flagged.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("No transactions flagged for this period. Nothing to report.", MARGIN, y);
    y += 8;
  }

  flagged.forEach((t, i) => {
    if (y > PAGE_H - 50) {
      drawFooter(doc, doc.internal.getNumberOfPages(), 0);
      doc.addPage();
      drawHeader(doc, "Suspicious Transaction Summary (cont.)");
      y = 38;
    }
    // Card-style block per flagged transaction
    doc.setDrawColor(LINE);
    doc.setFillColor("#fafaf8");
    doc.roundedRect(MARGIN, y, CONTENT_W, 32, 2, 2, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(INK);
    const ref = `[${i + 1}] ${t.ref || (t.id ? `QU-${t.id.slice(0, 8).toUpperCase()}` : "—")}`;
    doc.text(ref, MARGIN + 4, y + 7);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(INK);
    doc.text(`${t.customer_name || "—"} · ${t.currency} ${parseFloat(t.amount || 0).toLocaleString()} → ${t.destination || "—"}`, MARGIN + 50, y + 7);

    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(fmtDate(t.created_at), PAGE_W - MARGIN - 4, y + 7, { align: "right" });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor("#991b1b");
    doc.text(`FLAG: ${t.flag_label || t.review_decision || "review"}`, MARGIN + 4, y + 14);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(INK);
    const reason = t.review_reason || t.flag_reason || "(no reason captured)";
    doc.text(reason.slice(0, 200), MARGIN + 4, y + 20, { maxWidth: CONTENT_W - 8 });

    if (t.operator_action || t.operator_review_override_reason) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(7.5);
      doc.setTextColor(MUTED);
      doc.text(`Operator action: ${t.operator_action || t.operator_review_override_reason || "—"}`, MARGIN + 4, y + 27, { maxWidth: CONTENT_W - 8 });
    }

    y += 36;
  });

  // Footer
  const noteY = PAGE_H - 28;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(MUTED);
  doc.text(`This summary is a starting point for STR filings (CBN, NFIU, SCUML). The operator is responsible for verifying each entry, adding supporting context, and submitting in the format required by their regulator. XaePay's AI compliance flags are advisory — they don't constitute a finding of suspicious activity, only an item for the operator to review.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("XaePay is not a regulated entity; this document does not constitute a regulatory filing.", MARGIN, noteY + 17, { maxWidth: CONTENT_W });
}

export function generateSuspiciousTransactionReportPdf(args) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildSuspiciousTransactionReportPage(doc, args);
  drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  return doc;
}

export function buildSuspiciousTransactionCsv(flagged) {
  const header = ["Reference", "Date", "Customer", "Amount", "Currency", "Destination", "Flag", "Reason", "Operator action"];
  const rows = flagged.map((t) => [
    t.ref || (t.id ? `QU-${t.id.slice(0, 8).toUpperCase()}` : ""),
    t.created_at ? new Date(t.created_at).toISOString().slice(0, 10) : "",
    t.customer_name || "",
    t.amount ?? "",
    t.currency || "",
    t.destination || "",
    t.flag_label || t.review_decision || "",
    t.review_reason || t.flag_reason || "",
    t.operator_action || t.operator_review_override_reason || "",
  ]);
  const escape = (v) => {
    const s = String(v ?? "");
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  return [header, ...rows].map((row) => row.map(escape).join(",")).join("\n");
}

// Build CSV from an array of transactions. Used alongside the PDF so the
// operator can also paste into Excel / regulator portals.
export function buildTransactionsCsv(transactions) {
  const header = ["Date", "Customer", "Customer phone", "Beneficiary", "Destination", "Amount", "Currency", "Rate (NGN/$)", "NGN total", "Status", "Cedar status", "Reference"];
  const rows = transactions.map((t) => [
    t.created_at ? new Date(t.created_at).toISOString().slice(0, 10) : "",
    t.customer_name || "",
    t.customer_phone || "",
    t.beneficiary || "",
    t.destination || "",
    t.amount ?? "",
    t.currency || "",
    t.rate ?? "",
    t.ngn_total ?? "",
    t.status || "",
    t.cedar_request_status || "",
    t.id ? `QU-${t.id.slice(0, 8).toUpperCase()}` : "",
  ]);
  const escape = (v) => {
    const s = String(v ?? "");
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  return [header, ...rows].map((row) => row.map(escape).join(",")).join("\n");
}

export const _refForFilename = ref;
