import { jsPDF } from "jspdf";

const INK = "#0a0b0d";
const PAPER = "#fcfbf7";
const LIME = "#d4f570";
const MUTED = "#6b7280";
const LINE = "#e5e7eb";
const EMERALD = "#0f5f3f";

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;

const fmtMoney = (n, ccy = "USD") =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: ccy, minimumFractionDigits: 2 }).format(n || 0);

const fmtNgn = (n) =>
  "NGN " + new Intl.NumberFormat("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n || 0);

const fmtDate = (iso) => {
  if (!iso) return "—";
  const d = new Date(iso);
  return d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
};

const fmtDateTime = (iso) => {
  if (!iso) return "—";
  const d = new Date(iso);
  return d.toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
};

const ref = (id) => "QU-" + String(id || "").slice(0, 4).toUpperCase();

function drawHeader(doc, title) {
  doc.setFillColor(INK);
  doc.rect(0, 0, PAGE_W, 24, "F");

  doc.setFillColor(LIME);
  doc.roundedRect(MARGIN, 8, 8, 8, 1.5, 1.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text("X", MARGIN + 4, 13.8, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(PAPER);
  doc.text("XaePay", MARGIN + 12, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(LIME);
  doc.text(title.toUpperCase(), PAGE_W - MARGIN, 14, { align: "right" });
}

function drawFooter(doc, page, total) {
  const y = PAGE_H - 12;
  doc.setDrawColor(LINE);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, y - 4, PAGE_W - MARGIN, y - 4);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(MUTED);
  doc.text("Generated by XaePay  |  Funds custody by licensed payment partner.  |  XaePay is a software/compliance layer that does not custody funds.", MARGIN, y);
  doc.text(`Page ${page} of ${total}`, PAGE_W - MARGIN, y, { align: "right" });
}

function drawLabelValue(doc, label, value, x, y, valueOpts = {}) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(MUTED);
  doc.text(label.toUpperCase(), x, y);

  doc.setFont(valueOpts.mono ? "courier" : "helvetica", valueOpts.bold ? "bold" : "normal");
  doc.setFontSize(valueOpts.size || 10);
  doc.setTextColor(valueOpts.color || INK);
  const v = String(value ?? "—");
  doc.text(v, x, y + 5);
  return y + (valueOpts.lineHeight || 11);
}

function buildPaymentInstructionsPage(doc, q) {
  drawHeader(doc, "Payment Instructions");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Deposit instructions", MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(`To complete your trade payment to ${q.beneficiary || "your supplier"}, deposit the amount below using the bank details on this page.`, MARGIN, y, { maxWidth: CONTENT_W });
  y += 12;

  doc.setFillColor(INK);
  doc.roundedRect(MARGIN, y, CONTENT_W, 40, 3, 3, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(LIME);
  doc.text("AMOUNT TO DEPOSIT", MARGIN + 8, y + 9);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(PAPER);
  const ngnTotal = q.ngn_total || (q.amount && q.rate ? q.amount * q.rate : 0);
  doc.text(fmtNgn(ngnTotal), MARGIN + 8, y + 24);

  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor(LIME);
  doc.text(`Reference  ${ref(q.id)}`, MARGIN + 8, y + 34);
  y += 50;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Bank details", MARGIN, y);
  y += 7;

  const bank = q.cedar_bank_details || {};
  const rows = [
    ["Bank name", bank.bank_name || bank.bankName || "—"],
    ["Account name", bank.account_name || bank.accountName || "—"],
    ["Account number", bank.account_number || bank.accountNumber || "—"],
    ["Sort / routing code", bank.sort_code || bank.sortCode || bank.routing_number || "—"],
    ["Reference (use exactly this)", ref(q.id)],
  ];

  doc.setDrawColor(LINE);
  doc.setLineWidth(0.2);
  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(label.toUpperCase(), MARGIN, y);

    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });

    doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
    y += 9;
  });
  y += 6;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("What happens next", MARGIN, y);
  y += 7;

  const steps = [
    "Use the exact reference above when making the deposit. Without it your payment may not be matched.",
    `Deposit must be made before ${fmtDateTime(q.expires_at)} for the locked rate to apply.`,
    `Once received, your operator (${q.bdc_name || "—"}) will release ${fmtMoney(q.amount, q.currency)} to ${q.beneficiary || "your supplier"} the same business day.`,
    "You will receive a WhatsApp + email notification at every step until funds are confirmed delivered.",
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(INK);
  steps.forEach((step, i) => {
    doc.text(`${i + 1}.`, MARGIN, y);
    const lines = doc.splitTextToSize(step, CONTENT_W - 6);
    doc.text(lines, MARGIN + 5, y);
    y += lines.length * 4.5 + 2;
  });

  y += 4;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`ISSUED BY  ${(q.bdc_name || "your operator").toUpperCase()}`, MARGIN, y);
  doc.text(`ISSUED  ${fmtDate(q.created_at)}`, PAGE_W - MARGIN, y, { align: "right" });
}

function buildInvoicePage(doc, q) {
  drawHeader(doc, "Invoice");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Invoice", MARGIN, y);

  doc.setFont("courier", "normal");
  doc.setFontSize(11);
  doc.setTextColor(MUTED);
  doc.text(ref(q.id), PAGE_W - MARGIN, y, { align: "right" });
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(`Issued ${fmtDate(q.created_at)}`, MARGIN, y);
  y += 14;

  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Issued by", q.bdc_name || "Your operator", MARGIN, y);
  drawLabelValue(doc, "Bill to", q.customer_name || "Customer", MARGIN + colW + 8, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(q.bdc_phone || "Operator contact", MARGIN, y + 11);
  doc.text([q.customer_phone, q.customer_email].filter(Boolean).join("  ·  ") || "—", MARGIN + colW + 8, y + 11);
  y += 22;

  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("DESCRIPTION", MARGIN, y);
  doc.text("AMOUNT", PAGE_W - MARGIN, y, { align: "right" });
  y += 5;
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  const desc = `Cross-border trade payment to ${q.beneficiary || "supplier"}${q.destination ? ` (${q.destination})` : ""}`;
  doc.text(desc, MARGIN, y, { maxWidth: CONTENT_W - 50 });
  doc.setFont("courier", "normal");
  doc.text(fmtMoney(q.amount, q.currency || "USD"), PAGE_W - MARGIN, y, { align: "right" });
  y += 12;

  if (q.invoice_payment_label) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(q.invoice_payment_label, MARGIN, y);
    y += 6;
  }

  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  const sumX = PAGE_W - MARGIN - 60;
  const drawSummaryRow = (label, value, opts = {}) => {
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(opts.size || 9);
    doc.setTextColor(opts.color || INK);
    doc.text(label, sumX, y);
    doc.setFont("courier", opts.bold ? "bold" : "normal");
    doc.text(value, PAGE_W - MARGIN, y, { align: "right" });
    y += opts.lineHeight || 6;
  };

  drawSummaryRow("Subtotal", fmtMoney(q.amount, q.currency || "USD"));
  drawSummaryRow("Exchange rate", `${(q.rate || 0).toFixed(2)} NGN / ${q.currency || "USD"}`);
  y += 2;
  doc.setDrawColor(INK);
  doc.line(sumX, y, PAGE_W - MARGIN, y);
  y += 6;
  const ngnTotal = q.ngn_total || (q.amount && q.rate ? q.amount * q.rate : 0);
  drawSummaryRow("Total", fmtNgn(ngnTotal), { bold: true, size: 12, lineHeight: 8 });

  y += 10;

  if (q.invoice_total_amount) {
    doc.setFillColor(255, 247, 213);
    doc.setDrawColor(252, 211, 77);
    doc.roundedRect(MARGIN, y, CONTENT_W, 14, 2, 2, "FD");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(INK);
    const note = `This payment is part of a larger invoice (full value ${fmtMoney(q.invoice_total_amount, q.invoice_total_currency || "USD")}). Track the full invoice with your operator.`;
    doc.text(note, MARGIN + 4, y + 9, { maxWidth: CONTENT_W - 8 });
    y += 18;
  }

  const noteY = PAGE_H - 35;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("This invoice records a cross-border trade payment facilitated by XaePay. Funds custody is provided by a licensed payment partner.", MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Questions? Reply to your operator on WhatsApp using the number you were quoted from.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateQuotePdf(quote) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildPaymentInstructionsPage(doc, quote);
  drawFooter(doc, 1, 2);
  doc.addPage();
  buildInvoicePage(doc, quote);
  drawFooter(doc, 2, 2);
  return doc;
}

export function downloadQuotePdf(doc, quoteId) {
  doc.save(`${ref(quoteId)}-XaePay.pdf`);
}

// === Compliance pack PDF =====================================================
// Per-customer compliance pack — issued by the operator to honor the
// Compliance Pro tier "quarterly compliance pack" deliverable. Lists all
// uploaded compliance documents, their status against tier requirements,
// and an audit summary.

function buildCompliancePackPage(doc, customer, docsByType, requirements, tier, operatorName) {
  drawHeader(doc, "Compliance Pack");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Compliance pack", MARGIN, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  const periodLabel = new Date().toLocaleDateString("en-GB", { month: "long", year: "numeric" });
  doc.text(`${customer.name || "Customer"} · ${periodLabel}`, MARGIN, y);
  y += 12;

  // Two-column header summary: customer | operator
  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Customer", customer.name || "—", MARGIN, y);
  drawLabelValue(doc, "Issued by", operatorName || "Operator", MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text([customer.phone, customer.email].filter(Boolean).join("  ·  ") || "—", MARGIN, y + 11);
  doc.text(`Tier: ${tier.toUpperCase()}`, MARGIN + colW + 8, y + 11);
  y += 22;

  // KYC + Cedar status pills
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Identity & licensing", MARGIN, y);
  y += 7;

  const idRows = [
    ["KYC status", (customer.cedar_kyc_status || customer.kyc_status || "Pending").toString().toUpperCase()],
    ["KYC tier", String(customer.kyc_tier ?? "0")],
    ["Cedar business ID", customer.cedar_business_id ? String(customer.cedar_business_id) : "—"],
    ["Customer type", customer.type || "—"],
  ];
  idRows.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(label.toUpperCase(), MARGIN, y);
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });
    doc.setDrawColor(LINE);
    doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
    y += 9;
  });
  y += 4;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Compliance documents", MARGIN, y);
  y += 6;

  if (!requirements || requirements.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("No documents required by this tier.", MARGIN, y);
    return;
  }

  // Table header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("DOCUMENT", MARGIN, y + 5);
  doc.text("ISSUED", MARGIN + 70, y + 5);
  doc.text("EXPIRES", MARGIN + 105, y + 5);
  doc.text("STATUS", PAGE_W - MARGIN, y + 5, { align: "right" });
  y += 8;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  requirements.forEach((r) => {
    const d = docsByType[r.docType];
    const expiresAt = d?.expires_at ? new Date(d.expires_at) : (d?.issued_at && r.refreshDays ? new Date(new Date(d.issued_at).getTime() + r.refreshDays * 86400000) : null);
    let status = "Missing";
    let statusColor = "#6b7280";
    if (d) {
      if (!r.refreshDays) { status = "Valid"; statusColor = EMERALD; }
      else if (expiresAt) {
        const days = Math.floor((expiresAt.getTime() - Date.now()) / 86400000);
        if (days < 0) { status = "Expired"; statusColor = "#991b1b"; }
        else if (days <= 14) { status = "Expiring"; statusColor = "#92400e"; }
        else { status = "Valid"; statusColor = EMERALD; }
      }
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(INK);
    doc.text(r.label, MARGIN, y, { maxWidth: 65 });

    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(d?.issued_at ? fmtDate(d.issued_at) : "—", MARGIN + 70, y);
    doc.text(expiresAt ? fmtDate(expiresAt.toISOString()) : (r.refreshDays ? "—" : "no expiry"), MARGIN + 105, y);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(statusColor);
    doc.text(status, PAGE_W - MARGIN, y, { align: "right" });

    doc.setDrawColor(LINE);
    doc.line(MARGIN, y + 3, PAGE_W - MARGIN, y + 3);
    y += 8;
  });

  // Footer note
  const noteY = PAGE_H - 35;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`This compliance pack reflects ${customer.name || "the customer"}'s document status at ${new Date().toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" })}.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Generated by XaePay's compliance agent. For Cedar Money's compliance team, verify each document against Cedar's records via the customer's onboarded business ID.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

// Per-transaction audit page — lists each completed transaction in the period
// with its trade-doc supporting docs status. Bank partners review this in the
// quarterly compliance check.
function buildTransactionsAuditPage(doc, customer, completedTransactions, transactionRequirements) {
  drawHeader(doc, "Transactions Audit");

  let y = 38;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Transactions audit", MARGIN, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(`${customer.name || "Customer"} · ${completedTransactions.length} completed transaction${completedTransactions.length === 1 ? "" : "s"} in this period`, MARGIN, y);
  y += 12;

  if (completedTransactions.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(MUTED);
    doc.text("No completed transactions in this audit period.", MARGIN, y);
    return;
  }

  completedTransactions.forEach((t, i) => {
    // Page-break if running low on space
    if (y > PAGE_H - 70) {
      drawFooter(doc, doc.internal.getNumberOfPages(), 0);
      doc.addPage();
      drawHeader(doc, "Transactions Audit (cont.)");
      y = 38;
    }

    const txRef = "QU-" + String(t.id || "").slice(0, 4).toUpperCase();
    const txTier = (t.review_tier || "verified").toLowerCase();
    const txReqs = transactionRequirements[txTier] || [];

    // Block header
    doc.setFillColor(247, 245, 240); // bone
    doc.roundedRect(MARGIN, y, CONTENT_W, 11, 1.5, 1.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(INK);
    doc.text(txRef, MARGIN + 3, y + 7);
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.text(`${fmtMoney(t.amount, t.currency || "USD")}  →  ${t.beneficiary || t.destination || "—"}`, MARGIN + 22, y + 7);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(`${txTier.toUpperCase()} · ${fmtDate(t.filled_at || t.created_at)}`, PAGE_W - MARGIN, y + 7, { align: "right" });
    y += 13;

    // Trade docs status
    if (txReqs.length === 0) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(MUTED);
      doc.text("No trade docs required at this tier.", MARGIN + 3, y);
      y += 7;
    } else {
      const txDocsByType = {};
      for (const d of t.docs || []) {
        if (!txDocsByType[d.doc_type]) txDocsByType[d.doc_type] = d;
      }
      txReqs.forEach((r) => {
        const present = !!txDocsByType[r.docType];
        const statusColor = present ? EMERALD : (r.severity === "hard" ? "#991b1b" : "#92400e");
        const statusLabel = present ? "Uploaded" : (r.severity === "hard" ? "MISSING" : "Recommended");
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(INK);
        doc.text(`  •  ${r.label}`, MARGIN + 3, y);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        doc.setTextColor(statusColor);
        doc.text(statusLabel, PAGE_W - MARGIN, y, { align: "right" });
        y += 6;
      });
    }
    y += 4;
  });

  // Audit footer
  if (y < PAGE_H - 30) {
    const noteY = PAGE_H - 30;
    doc.setDrawColor(LINE);
    doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text("Each transaction's trade documents back up the original invoice. Documents marked MISSING for hard-required types should be remediated before the next quarterly review window closes.", MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  }
}

export function generateCompliancePackPdf({ customer, docs, requirements, tier, operatorName, completedTransactions, transactionRequirements }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  // Group customer-level docs by doc_type, keeping the latest per type
  const docsByType = {};
  for (const d of docs || []) {
    const existing = docsByType[d.doc_type];
    if (!existing) docsByType[d.doc_type] = d;
    else {
      const exp1 = existing.expires_at || existing.issued_at || existing.created_at || "";
      const exp2 = d.expires_at || d.issued_at || d.created_at || "";
      if (exp2 > exp1) docsByType[d.doc_type] = d;
    }
  }
  buildCompliancePackPage(doc, customer, docsByType, requirements, tier || "pro", operatorName);
  drawFooter(doc, 1, 0); // pageCount filled in at save time

  // Add transactions audit page if we have completed transactions to report on
  if (completedTransactions && completedTransactions.length > 0 && transactionRequirements) {
    doc.addPage();
    buildTransactionsAuditPage(doc, customer, completedTransactions, transactionRequirements);
    drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  }
  return doc;
}

// === Transaction confirmation PDF ============================================
// Auto-generated receipt for a completed transaction. Available to both
// operator and customer the moment the transaction's status flips to filled
// (or Cedar reports COMPLETED / payout ARRIVED). Independent of Cedar's MT103 —
// the MT103 is a separate bank-confirmation doc that gets uploaded into the
// transaction's supporting documents once the operator has it.

function buildTransactionConfirmationPage(doc, q, operatorName) {
  drawHeader(doc, "Transaction Confirmation");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Confirmation", MARGIN, y);

  doc.setFont("courier", "normal");
  doc.setFontSize(11);
  doc.setTextColor(MUTED);
  doc.text(ref(q.id), PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(`Status: COMPLETED · Issued ${fmtDateTime(q.filled_at || q.cedar_request_status_updated_at || q.created_at)}`, MARGIN, y);
  y += 12;

  // Big amount card
  doc.setFillColor(INK);
  doc.roundedRect(MARGIN, y, CONTENT_W, 38, 3, 3, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(LIME);
  doc.text("AMOUNT PROCESSED", MARGIN + 8, y + 9);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(PAPER);
  doc.text(fmtMoney(q.amount, q.currency || "USD"), MARGIN + 8, y + 24);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor(LIME);
  doc.text(`Customer paid  ${fmtNgn(q.ngn_total)}  @  ₦${parseFloat(q.rate || 0).toFixed(2)}/$`, MARGIN + 8, y + 33);
  y += 48;

  // Parties
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Parties", MARGIN, y);
  y += 6;

  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Customer", q.customer_name || "—", MARGIN, y);
  drawLabelValue(doc, "Recipient / supplier", q.beneficiary || "—", MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text([q.customer_phone, q.customer?.email].filter(Boolean).join("  ·  ") || "—", MARGIN, y + 11);
  doc.text(q.destination || "—", MARGIN + colW + 8, y + 11);
  y += 20;

  drawLabelValue(doc, "Issued by", operatorName || q.bdc_name || "Operator", MARGIN, y);
  drawLabelValue(doc, "Settled via", "Licensed payment partner", MARGIN + colW + 8, y);
  y += 16;

  // Transaction details table
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Transaction details", MARGIN, y);
  y += 7;

  const rows = [
    ["Reference", ref(q.id)],
    ["Amount", `${fmtMoney(q.amount, q.currency || "USD")}`],
    ["Customer rate", `₦${parseFloat(q.rate || 0).toFixed(2)} / $`],
    ["Customer paid (NGN)", fmtNgn(q.ngn_total)],
    ["Purpose", q.cedar_purpose || "GOODS_PURCHASED"],
    ["Status", "COMPLETED"],
    ["Completed at", fmtDateTime(q.filled_at || q.cedar_request_status_updated_at)],
  ];
  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(label.toUpperCase(), MARGIN, y);
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });
    doc.setDrawColor(LINE);
    doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
    y += 9;
  });

  // Bank details (if present from Cedar response)
  const bank = q.cedar_bank_details || {};
  const bankName = bank.bank_name || bank.bankName;
  if (bankName) {
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(INK);
    doc.text("Settlement route", MARGIN, y);
    y += 7;
    const bankRows = [
      ["Bank", bankName],
      ["Account name", bank.account_name || bank.accountName || "—"],
      ["Account number", bank.account_number || bank.accountNumber || "—"],
      ["Reference", ref(q.id)],
    ];
    bankRows.forEach(([label, value]) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text(label.toUpperCase(), MARGIN, y);
      doc.setFont("courier", "normal");
      doc.setFontSize(10);
      doc.setTextColor(INK);
      doc.text(String(value), PAGE_W - MARGIN, y, { align: "right" });
      doc.setDrawColor(LINE);
      doc.line(MARGIN, y + 2.5, PAGE_W - MARGIN, y + 2.5);
      y += 9;
    });
  }

  // Footer note
  const noteY = PAGE_H - 35;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("This confirmation is generated automatically by XaePay when a cross-border trade payment completes. The MT103 / SWIFT wire confirmation is a separate document issued by the licensed payment partner; once available it will be attached to this transaction.", MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Powered by XaePay · Software/compliance layer · Funds custody by licensed payment partner.", MARGIN, noteY + 17, { maxWidth: CONTENT_W });
}

export function generateTransactionConfirmationPdf({ quote, operatorName }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildTransactionConfirmationPage(doc, quote, operatorName);
  drawFooter(doc, 1, 1);
  return doc;
}

export function downloadTransactionConfirmationPdf(doc, quote) {
  doc.save(`${ref(quote.id)}-confirmation-XaePay.pdf`);
}

export function downloadCompliancePackPdf(doc, customer) {
  const safeName = (customer?.name || "Customer").replace(/[^\w]+/g, "_");
  const period = new Date().toLocaleDateString("en-GB", { month: "short", year: "numeric" }).replace(/\s+/g, "_");
  doc.save(`${safeName}_compliance_pack_${period}.pdf`);
}

// === Invoice PDF =============================================================
// Operator-issued invoice for goods or services rendered. Customer reviews +
// hits "Pay this invoice" in their portal, which kicks off the existing
// rate-quote flow with the invoice's amount + currency prefilled. PDF is
// downloadable + emailable.

function buildInvoicePdfPage(doc, invoice, items) {
  drawHeader(doc, "Invoice");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Invoice", MARGIN, y);

  doc.setFont("courier", "normal");
  doc.setFontSize(12);
  doc.setTextColor(MUTED);
  doc.text(invoice.invoice_number || "—", PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  const issued = invoice.issue_date ? fmtDate(invoice.issue_date) : fmtDate(invoice.created_at);
  const due = invoice.due_date ? `· Due ${fmtDate(invoice.due_date)}` : "";
  doc.text(`Issued ${issued} ${due}`, MARGIN, y);
  y += 14;

  // Issued by / Bill to
  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Issued by", invoice.operator_name || "Operator", MARGIN, y);
  drawLabelValue(doc, "Bill to", invoice.customer_name || "Customer", MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("Via XaePay", MARGIN, y + 11);
  doc.text([invoice.customer_phone, invoice.customer_email].filter(Boolean).join("  ·  ") || "—", MARGIN + colW + 8, y + 11, { maxWidth: colW });
  y += 22;

  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  // Items table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("DESCRIPTION", MARGIN, y);
  doc.text("QTY", MARGIN + 105, y, { align: "right" });
  doc.text("UNIT", MARGIN + 135, y, { align: "right" });
  doc.text("AMOUNT", PAGE_W - MARGIN, y, { align: "right" });
  y += 5;
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 7;

  const ccy = invoice.currency || "USD";
  const sortedItems = [...(items || [])].sort((a, b) => (a.position || 0) - (b.position || 0));
  sortedItems.forEach((it) => {
    if (y > PAGE_H - 80) {
      drawFooter(doc, doc.internal.getNumberOfPages(), 0);
      doc.addPage();
      drawHeader(doc, "Invoice (cont.)");
      y = 38;
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    const descLines = doc.splitTextToSize(it.description || "—", 95);
    doc.text(descLines, MARGIN, y);

    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    doc.text(String(parseFloat(it.quantity || 1)), MARGIN + 105, y, { align: "right" });
    doc.text(fmtMoney(parseFloat(it.unit_price || 0), ccy), MARGIN + 135, y, { align: "right" });
    doc.setFont("courier", "bold");
    doc.text(fmtMoney(parseFloat(it.amount || 0), ccy), PAGE_W - MARGIN, y, { align: "right" });

    y += Math.max(descLines.length * 4, 6) + 4;
  });

  // Totals
  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  const sumX = PAGE_W - MARGIN - 60;
  const sumRow = (label, value, bold) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(bold ? 12 : 9);
    doc.setTextColor(INK);
    doc.text(label, sumX, y);
    doc.setFont("courier", bold ? "bold" : "normal");
    doc.text(value, PAGE_W - MARGIN, y, { align: "right" });
    y += bold ? 8 : 6;
  };

  sumRow("Subtotal", fmtMoney(parseFloat(invoice.subtotal || 0), ccy));
  if (parseFloat(invoice.tax || 0) > 0) {
    sumRow("Tax", fmtMoney(parseFloat(invoice.tax || 0), ccy));
  }
  y += 2;
  doc.setDrawColor(INK);
  doc.line(sumX, y, PAGE_W - MARGIN, y);
  y += 6;
  sumRow(`Total (${ccy})`, fmtMoney(parseFloat(invoice.total || 0), ccy), true);

  // Payment methods (operator-configured per-invoice instructions)
  const methods = Array.isArray(invoice.payment_methods) ? invoice.payment_methods : [];
  if (methods.length > 0) {
    y += 6;
    if (y > PAGE_H - 60) { drawFooter(doc, doc.internal.getNumberOfPages(), 0); doc.addPage(); drawHeader(doc, "Invoice (cont.)"); y = 38; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text("Payment options", MARGIN, y);
    y += 6;
    const TYPE_LABELS = {
      zelle: "Zelle", ach: "ACH transfer", wire_us: "Domestic wire (US)", apple_pay: "Apple Pay / Cash App",
      check: "Certified check", card_link: "Card payment link", bank_ngn: "Nigerian bank transfer",
      ussd: "USSD", crossborder: "International (XaePay)", other: "Other",
    };
    methods.forEach((m) => {
      if (y > PAGE_H - 50) { drawFooter(doc, doc.internal.getNumberOfPages(), 0); doc.addPage(); drawHeader(doc, "Invoice (cont.)"); y = 38; }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(INK);
      const label = (TYPE_LABELS[m.type] || m.type) + (m.label ? ` · ${m.label}` : "");
      doc.text(label, MARGIN, y);
      y += 4.5;
      if (m.instructions) {
        doc.setFont("courier", "normal");
        doc.setFontSize(8.5);
        doc.setTextColor(MUTED);
        const lines = doc.splitTextToSize(m.instructions, CONTENT_W);
        doc.text(lines, MARGIN, y);
        y += lines.length * 4 + 2;
      } else if (m.type === "crossborder") {
        doc.setFont("helvetica", "italic");
        doc.setFontSize(8.5);
        doc.setTextColor(MUTED);
        doc.text("Pay via cross-border rate quote in your XaePay portal.", MARGIN, y);
        y += 4 + 2;
      }
      y += 2;
    });
  }

  // Notes
  if (invoice.notes) {
    y += 6;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text("Notes", MARGIN, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    const noteLines = doc.splitTextToSize(invoice.notes, CONTENT_W);
    doc.text(noteLines, MARGIN, y);
    y += noteLines.length * 4.5 + 4;
  }

  // Status pill (if not draft)
  if (invoice.status && invoice.status !== "draft") {
    const pillBg = invoice.status === "paid" ? "#d1fae5" : invoice.status === "void" ? "#fee2e2" : "#fef3c7";
    const pillColor = invoice.status === "paid" ? "#065f46" : invoice.status === "void" ? "#991b1b" : "#92400e";
    doc.setFillColor(pillBg);
    doc.roundedRect(MARGIN, y, 30, 7, 2, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(pillColor);
    doc.text(invoice.status.toUpperCase(), MARGIN + 15, y + 4.7, { align: "center" });
  }

  // Footer
  const noteY = PAGE_H - 30;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`Pay using any of the payment options above, then confirm the payment in your XaePay customer portal. The operator who issued this invoice will verify receipt before the invoice is marked paid.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Issued via XaePay · Operator-issued invoice · XaePay does not custody local-rail payments.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateInvoicePdf({ invoice, items }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildInvoicePdfPage(doc, invoice, items);
  drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  return doc;
}

export function downloadInvoicePdf(doc, invoice) {
  const num = (invoice?.invoice_number || "invoice").replace(/[^\w-]+/g, "_");
  doc.save(`${num}-XaePay.pdf`);
}

// =============================================================================
// Receipt — auto-generated when an invoice is marked paid. Acts as the
// operator's proof-of-receipt to the customer. Receipt number is derived from
// the invoice number (INV-XXXX → INV-XXXX/R) so we don't need a new sequence.
// `payment` is the confirmed invoice_payments row (or a synthesized object for
// cross-border quotes that auto-pay through the Cedar trigger).
// =============================================================================

const RECEIPT_METHOD_LABELS = {
  zelle: "Zelle", ach: "ACH transfer", wire_us: "Domestic wire (US)", apple_pay: "Apple Pay / Cash App",
  check: "Certified check", card_link: "Card payment", bank_ngn: "Nigerian bank transfer",
  ussd: "USSD", crossborder: "International (XaePay)", other: "Other",
};

function buildReceiptPdfPage(doc, invoice, items, payment) {
  drawHeader(doc, "Receipt");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Receipt", MARGIN, y);

  const receiptNum = `${invoice.invoice_number || "INV"}/R`;
  doc.setFont("courier", "normal");
  doc.setFontSize(12);
  doc.setTextColor(MUTED);
  doc.text(receiptNum, PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  const issuedAt = invoice.receipt_issued_at || invoice.paid_at || new Date().toISOString();
  doc.text(`Issued ${fmtDateTime(issuedAt)}`, MARGIN, y);
  y += 14;

  // Big paid amount stripe
  const ccy = invoice.currency || payment?.currency || "USD";
  const paidAmt = parseFloat(payment?.amount || invoice.total || 0);
  doc.setFillColor(EMERALD);
  doc.roundedRect(MARGIN, y, CONTENT_W, 26, 3, 3, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#d1fae5");
  doc.text("AMOUNT RECEIVED", MARGIN + 6, y + 8);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor("#ffffff");
  doc.text(fmtMoney(paidAmt, ccy), MARGIN + 6, y + 19);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor("#d1fae5");
  doc.text(`PAID · ${fmtDate(invoice.paid_at || issuedAt)}`, PAGE_W - MARGIN - 6, y + 19, { align: "right" });
  y += 34;

  // Issued by / Issued to
  const colW = (CONTENT_W - 8) / 2;
  drawLabelValue(doc, "Received from", invoice.customer_name || "Customer", MARGIN, y);
  drawLabelValue(doc, "Received by", invoice.operator_name || "Operator", MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text([invoice.customer_phone, invoice.customer_email].filter(Boolean).join("  ·  ") || "—", MARGIN, y + 11, { maxWidth: colW });
  doc.text("Via XaePay", MARGIN + colW + 8, y + 11);
  y += 22;

  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  // Payment details
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text("Payment details", MARGIN, y);
  y += 7;
  const methodLabel = payment?.method_type ? (RECEIPT_METHOD_LABELS[payment.method_type] || payment.method_type) : "—";
  const detailRow = (label, value) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text(label, MARGIN, y);
    doc.setFont("courier", "normal");
    doc.setTextColor(INK);
    doc.text(value || "—", PAGE_W - MARGIN, y, { align: "right" });
    y += 6;
  };
  detailRow("Method", methodLabel + (payment?.method_label ? ` · ${payment.method_label}` : ""));
  if (payment?.reference) detailRow("Reference", payment.reference);
  detailRow("Invoice", invoice.invoice_number || "—");
  if (invoice.issue_date) detailRow("Invoice issued", fmtDate(invoice.issue_date));
  detailRow("Payment confirmed", fmtDateTime(invoice.paid_at || issuedAt));
  y += 4;

  // Itemized recap so the receipt is self-contained
  if (Array.isArray(items) && items.length > 0) {
    doc.setDrawColor(LINE);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(INK);
    doc.text("What this covers", MARGIN, y);
    y += 7;
    const sortedItems = [...items].sort((a, b) => (a.position || 0) - (b.position || 0));
    sortedItems.forEach((it) => {
      if (y > PAGE_H - 50) { drawFooter(doc, doc.internal.getNumberOfPages(), 0); doc.addPage(); drawHeader(doc, "Receipt (cont.)"); y = 38; }
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(INK);
      const descLines = doc.splitTextToSize(it.description || "—", CONTENT_W - 40);
      doc.text(descLines, MARGIN, y);
      doc.setFont("courier", "bold");
      doc.setFontSize(9);
      doc.text(fmtMoney(parseFloat(it.amount || 0), ccy), PAGE_W - MARGIN, y, { align: "right" });
      y += Math.max(descLines.length * 4, 6) + 2;
    });
  }

  // Status confirmation
  y += 4;
  doc.setFillColor("#d1fae5");
  doc.roundedRect(MARGIN, y, 36, 7, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor("#065f46");
  doc.text("RECEIPT ISSUED", MARGIN + 18, y + 4.7, { align: "center" });

  // Footer
  const noteY = PAGE_H - 30;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`This receipt acknowledges that ${invoice.operator_name || "the operator"} has received payment for invoice ${invoice.invoice_number || ""}. Keep this document for your records.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Issued via XaePay · Operator-confirmed receipt · Not a tax document.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateReceiptPdf({ invoice, items, payment }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildReceiptPdfPage(doc, invoice, items, payment);
  drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  return doc;
}

export function downloadReceiptPdf(doc, invoice) {
  const num = (invoice?.invoice_number || "receipt").replace(/[^\w-]+/g, "_");
  doc.save(`${num}-R-XaePay.pdf`);
}

// =============================================================================
// Recipient receipt — operator-issued confirmation that a payout was sent to a
// recipient. Distinct from the invoice receipt (which acknowledges money
// received from a customer). Triggered when a quote moves into a completed
// state (status=filled / cedar COMPLETED / cedar ARRIVED).
// =============================================================================

function buildRecipientReceiptPage(doc, quote, recipient) {
  drawHeader(doc, "Payment Confirmation");

  let y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(INK);
  doc.text("Payment sent", MARGIN, y);

  const ref = `QU-${(quote.id || "").slice(0, 8).toUpperCase()}/R`;
  doc.setFont("courier", "normal");
  doc.setFontSize(12);
  doc.setTextColor(MUTED);
  doc.text(ref, PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  const issuedAt = quote.recipient_receipt_issued_at || quote.cedar_request_status_updated_at || new Date().toISOString();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(`Issued ${fmtDateTime(issuedAt)}`, MARGIN, y);
  y += 14;

  // Amount stripe
  const ccy = quote.currency || "USD";
  const amt = parseFloat(quote.amount || 0);
  doc.setFillColor(EMERALD);
  doc.roundedRect(MARGIN, y, CONTENT_W, 26, 3, 3, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#d1fae5");
  doc.text("AMOUNT SENT TO YOU", MARGIN + 6, y + 8);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor("#ffffff");
  doc.text(fmtMoney(amt, ccy), MARGIN + 6, y + 19);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor("#d1fae5");
  doc.text(`PAID · ${fmtDate(issuedAt)}`, PAGE_W - MARGIN - 6, y + 19, { align: "right" });
  y += 34;

  // From / To columns
  const colW = (CONTENT_W - 8) / 2;
  const recipientName = recipient?.full_name || recipient?.legal_business_name || quote.beneficiary || "Recipient";
  const senderName = quote.customer_name || "Customer";
  const operatorName = quote.bdc_name || "XaeccoX";
  drawLabelValue(doc, "Paid by", senderName, MARGIN, y);
  drawLabelValue(doc, "Paid to", recipientName, MARGIN + colW + 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`via ${operatorName} (XaePay)`, MARGIN, y + 11);
  if (recipient?.bank_name || recipient?.bank_account_number) {
    const bankLine = [recipient.bank_name, recipient.bank_account_number ? `· ${recipient.bank_account_number.slice(-4).padStart(recipient.bank_account_number.length, "•")}` : ""].filter(Boolean).join(" ");
    doc.text(bankLine, MARGIN + colW + 8, y + 11, { maxWidth: colW });
  }
  y += 22;

  doc.setDrawColor(LINE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  // Payment details
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text("Payment details", MARGIN, y);
  y += 7;

  const detailRow = (label, value) => {
    if (!value) return;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text(label, MARGIN, y);
    doc.setFont("courier", "normal");
    doc.setTextColor(INK);
    const lines = doc.splitTextToSize(String(value), CONTENT_W - 70);
    doc.text(lines, PAGE_W - MARGIN, y, { align: "right" });
    y += Math.max(lines.length * 5, 6);
  };
  detailRow("Reference", ref);
  detailRow("Transaction ID", quote.id || null);
  if (quote.cedar_business_request_id) detailRow("Partner reference", quote.cedar_business_request_id);
  detailRow("Sender", senderName);
  detailRow("Recipient", recipientName);
  if (recipient?.bank_name) detailRow("Bank", recipient.bank_name);
  if (recipient?.bank_account_number) detailRow("Account", recipient.bank_account_number);
  if (quote.purpose_note) detailRow("Purpose", quote.purpose_note);
  detailRow("Settled", fmtDateTime(issuedAt));
  y += 6;

  // Status pill
  doc.setFillColor("#d1fae5");
  doc.roundedRect(MARGIN, y, 36, 7, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor("#065f46");
  doc.text("PAYMENT SETTLED", MARGIN + 18, y + 4.7, { align: "center" });

  // Footer
  const noteY = PAGE_H - 30;
  doc.setDrawColor(LINE);
  doc.line(MARGIN, noteY, PAGE_W - MARGIN, noteY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`This confirms that ${senderName} has sent the amount above to ${recipientName} via ${operatorName} on XaePay. Keep this document for your records.`, MARGIN, noteY + 5, { maxWidth: CONTENT_W });
  doc.text("Issued via XaePay · Operator-confirmed payout · Not a tax document.", MARGIN, noteY + 13, { maxWidth: CONTENT_W });
}

export function generateRecipientReceiptPdf({ quote, recipient }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  buildRecipientReceiptPage(doc, quote, recipient || {});
  drawFooter(doc, doc.internal.getNumberOfPages(), 0);
  return doc;
}

export function downloadRecipientReceiptPdf(doc, quote) {
  const id = (quote?.id || "receipt").slice(0, 8);
  doc.save(`payout-${id}-R-XaePay.pdf`);
}

export const _refForFilename = ref;
